import type { B1GrammarTopic } from "./grammar-b1";

export const A2_GRAMMAR_TOPICS: B1GrammarTopic[] = [
  {
    id: "a2-perfekt",
    title: "Perfekt",
    subtitle: "Konuşma Dilinde Geçmiş Zaman",
    explanation: "Perfekt, konuşma dilinde geçmişi anlatmak için kullanılan en yaygın geçmiş zaman kipidir. haben veya sein (çekimli) + Partizip II yapısıyla kurulur.",
    rules: [
      {
        heading: "Perfekt Yapısı",
        body: "Perfekt = haben/sein (çekimli, 2. pozisyonda) + Partizip II (sona). Geçmişte yaşanan olaylar için kullanılır.",
        examples: [
          { de: "Ich habe das Buch gelesen.", tr: "Kitabı okudum." },
          { de: "Er ist nach Berlin gefahren.", tr: "Berlin'e gitti." },
          { de: "Wir haben Kaffee getrunken.", tr: "Kahve içtik." },
        ],
      },
      {
        heading: "haben mi, sein mi?",
        body: "Yer değişimi (gehen, kommen, fahren) ve hal değişimi (werden, einschlafen) → sein. Diğer geçişli/geçişsiz fiiller → haben.",
        examples: [
          { de: "Ich bin ins Kino gegangen.", tr: "Sinemaya gittim. (sein)" },
          { de: "Sie hat das Essen gekocht.", tr: "Yemeği pişirdi. (haben)" },
          { de: "Er ist müde geworden.", tr: "Yoruldu / yorgun oldu. (sein - hal değişimi)" },
        ],
      },
      {
        heading: "Partizip II Türetme",
        body: "Düzenli: ge- + Stamm + -t → gemacht. Düzensiz: ge- + Stamm + -en → geschrieben. Trennbar: Önek + ge + ...: aufgemacht. -ieren: -iert (ge- yok): studiert.",
        examples: [
          { de: "machen → gemacht", tr: "yapmak → yapıldı" },
          { de: "schreiben → geschrieben", tr: "yazmak → yazıldı" },
          { de: "aufmachen → aufgemacht", tr: "açmak → açıldı" },
        ],
        table: {
          headers: ["Tür", "Kural", "Örnek"],
          rows: [
            ["Düzenli", "ge- + Stamm + -t", "spielen → gespielt"],
            ["Düzensiz", "ge- + Stamm + -en", "trinken → getrunken"],
            ["Trennbar", "Önek + ge + -t/-en", "aufmachen → aufgemacht"],
            ["-ieren", "Sadece -iert", "studieren → studiert"],
          ],
        },
      },
    ],
    exercises: {
      multipleChoice: [
        {
          id: 1,
          question: "Ich ___ gestern ins Kino gegangen.",
          options: ["habe", "bin", "hatte", "wurde"],
          correct: 1,
          explanation: "gehen = yer değişimi → sein; ich → bin.",
        },
        {
          id: 2,
          question: "Er ___ das Buch gelesen.",
          options: ["ist", "bin", "hat", "sind"],
          correct: 2,
          explanation: "lesen = yer/hal değişimi yok → haben; er → hat.",
        },
        {
          id: 3,
          question: "Partizip II von 'schreiben' ist:",
          options: ["geschreibt", "geschrieben", "geSchreiben", "schriebte"],
          correct: 1,
          explanation: "Düzensiz fiil: schreiben → geschrieben.",
        },
        {
          id: 4,
          question: "Wir ___ Kaffee getrunken.",
          options: ["sind", "hat", "haben", "seid"],
          correct: 2,
          explanation: "trinken → yer değişimi yok → haben; wir → haben.",
        },
        {
          id: 5,
          question: "Sie ___ früh aufgestanden.",
          options: ["hat", "haben", "ist", "war"],
          correct: 2,
          explanation: "aufstehen = hal değişimi → sein; sie (tekil) → ist.",
        },
        {
          id: 6,
          question: "Partizip II von 'kaufen' ist:",
          options: ["gekaufen", "kauft", "gekauft", "gekaüft"],
          correct: 2,
          explanation: "Düzenli fiil: ge- + kauf + -t = gekauft.",
        },
        {
          id: 7,
          question: "Er ___ nach Berlin gefahren.",
          options: ["hat", "haben", "ist", "sein"],
          correct: 2,
          explanation: "fahren = yer değişimi → sein; er → ist.",
        },
        {
          id: 8,
          question: "-ieren fiillerinde Partizip II nasıl yapılır?",
          options: ["ge- + -iert", "sadece -iert (ge- yok)", "ge- + -t", "-ieren kalır"],
          correct: 1,
          explanation: "studieren → studiert; ge- eklenmez.",
        },
      ],
      fillInBlank: [
        {
          id: 1,
          before: "Ich",
          after: "heute Fußball gespielt.",
          answer: "habe",
          hint: "spielen → yer değişimi yok → haben; ich → habe",
        },
        {
          id: 2,
          before: "Wir",
          after: "nach Hause gefahren.",
          answer: "sind",
          hint: "fahren = yer değişimi → sein; wir → sind",
        },
        {
          id: 3,
          before: "Er hat das Fenster",
          after: ".",
          answer: "geöffnet",
          hint: "öffnen → ge- + öffn + -t = geöffnet",
        },
        {
          id: 4,
          before: "Sie ist gestern",
          after: ".",
          answer: "eingeschlafen",
          hint: "einschlafen = hal değişimi → sein; trennbar: ein+ge+schlafen",
        },
        {
          id: 5,
          before: "Du hast sehr gut",
          after: ".",
          answer: "geschrieben",
          hint: "schreiben → düzensiz → geschrieben",
        },
      ],
    },
  },
  {
    id: "a2-starke-verben",
    title: "Starke Verben Präsens",
    subtitle: "Güçlü Fiiller — Kök Değişimi",
    explanation: "Bazı Almanca fiillerin 2. ve 3. tekil şahıs (du/er) çekimlerinde kök ünlüsü değişir. Bu fiillere 'starke Verben' (güçlü fiiller) denir.",
    rules: [
      {
        heading: "Ünlü Değişim Tipleri",
        body: "a → ä: fahren (du fährst, er fährt), schlafen (du schläfst). e → i: geben (du gibst, er gibt), sprechen (du sprichst). e → ie: lesen (du liest, er liest), sehen (du siehst).",
        examples: [
          { de: "du fährst, er fährt (fahren)", tr: "sen gidiyorsun, o gidiyor" },
          { de: "du gibst, er gibt (geben)", tr: "sen veriyorsun, o veriyor" },
          { de: "du liest, er liest (lesen)", tr: "sen okuyorsun, o okuyor" },
        ],
        table: {
          headers: ["Fiil", "Değişim", "du", "er/sie/es"],
          rows: [
            ["fahren", "a→ä", "fährst", "fährt"],
            ["schlafen", "a→ä", "schläfst", "schläft"],
            ["geben", "e→i", "gibst", "gibt"],
            ["sprechen", "e→i", "sprichst", "spricht"],
            ["lesen", "e→ie", "liest", "liest"],
            ["sehen", "e→ie", "siehst", "sieht"],
            ["laufen", "au→äu", "läufst", "läuft"],
            ["werden", "e→i", "wirst", "wird"],
          ],
        },
      },
      {
        heading: "Önemli İstisnalar",
        body: "essen: du isst, er isst. treffen: du triffst, er trifft. helfen: du hilfst, er hilft. werden: du wirst, er wird (tamamen düzensiz). 1. ve çoğul şahıslar değişmez.",
        examples: [
          { de: "Was isst du zum Mittagessen?", tr: "Öğle yemeğinde ne yiyorsun?" },
          { de: "Er wird Arzt.", tr: "O doktor olacak." },
          { de: "Sie trifft ihre Freundin.", tr: "Arkadaşıyla buluşuyor." },
        ],
      },
    ],
    exercises: {
      multipleChoice: [
        {
          id: 1,
          question: "Er ___ sehr schnell. (laufen)",
          options: ["lauft", "läuft", "laufst", "laufen"],
          correct: 1,
          explanation: "laufen: au→äu; er/sie/es → läuft.",
        },
        {
          id: 2,
          question: "Du ___ zu viel. (schlafen)",
          options: ["schlafen", "schläfst", "schlafst", "schläfen"],
          correct: 1,
          explanation: "schlafen: a→ä; du → schläfst.",
        },
        {
          id: 3,
          question: "Was ___ du zum Frühstück? (essen)",
          options: ["esst", "isst", "essst", "esst"],
          correct: 1,
          explanation: "essen: e→i; du isst.",
        },
        {
          id: 4,
          question: "Er ___ mir bei den Hausaufgaben. (helfen)",
          options: ["helft", "hilfst", "hilft", "helfen"],
          correct: 2,
          explanation: "helfen: e→i; er/sie/es → hilft.",
        },
        {
          id: 5,
          question: "Sie ___ ein Buch. (lesen)",
          options: ["lest", "liest", "lesst", "lieset"],
          correct: 1,
          explanation: "lesen: e→ie; er/sie/es → liest.",
        },
        {
          id: 6,
          question: "Du ___ gut Deutsch. (sprechen)",
          options: ["sprichst", "sprechst", "sprichest", "sprecht"],
          correct: 0,
          explanation: "sprechen: e→i; du → sprichst.",
        },
        {
          id: 7,
          question: "Er ___ Arzt. (werden)",
          options: ["werdet", "wird", "wirst", "werde"],
          correct: 1,
          explanation: "werden: er/sie/es → wird (düzensiz).",
        },
        {
          id: 8,
          question: "Du ___ deinen Freund im Café. (treffen)",
          options: ["triffst", "treffst", "trifft", "treffest"],
          correct: 0,
          explanation: "treffen: e→i; du → triffst.",
        },
      ],
      fillInBlank: [
        {
          id: 1,
          before: "Er",
          after: "jeden Tag ins Büro. (fahren)",
          answer: "fährt",
          hint: "fahren: a→ä; er → fährt",
        },
        {
          id: 2,
          before: "Du",
          after: "das Buch auf dem Tisch. (sehen)",
          answer: "siehst",
          hint: "sehen: e→ie; du → siehst",
        },
        {
          id: 3,
          before: "Was",
          after: "du mir? (geben)",
          answer: "gibst",
          hint: "geben: e→i; du → gibst",
        },
        {
          id: 4,
          before: "Sie",
          after: "Lehrerin. (werden)",
          answer: "wird",
          hint: "werden: er/sie/es → wird",
        },
        {
          id: 5,
          before: "Er",
          after: "gern Pizza. (essen)",
          answer: "isst",
          hint: "essen: e→i; er → isst",
        },
      ],
    },
  },
  {
    id: "a2-dativ",
    title: "Dativ",
    subtitle: "Yönelme Hali — Edatlar ve Fiiller",
    explanation: "Dativ (Wem? — Kime?), belirli edatlar ve bazı fiillerden sonra kullanılır. Maskulin ve nötr tekilde 'dem', feminin tekilde 'der' olur.",
    rules: [
      {
        heading: "Dativ Artikelleri",
        body: "Maskulin: dem/einem | Feminin: der/einer | Nötr: dem/einem | Plural: den (isimde -n eki). Kişi zamirleri: ich→mir, du→dir, er→ihm, sie→ihr, es→ihm, wir→uns, ihr→euch, sie→ihnen.",
        examples: [
          { de: "Ich fahre mit dem Zug.", tr: "Trenle gidiyorum." },
          { de: "Er wohnt bei seiner Mutter.", tr: "Annesinin yanında yaşıyor." },
          { de: "Das Buch gehört dem Kind.", tr: "Kitap çocuğa ait." },
        ],
        table: {
          headers: ["Genus", "Belirli Dativ", "Belirsiz Dativ"],
          rows: [
            ["Maskulin", "dem", "einem"],
            ["Feminin", "der", "einer"],
            ["Nötr", "dem", "einem"],
            ["Plural", "den (+n)", "—"],
          ],
        },
      },
      {
        heading: "Dativ Gerektiren Edatlar",
        body: "aus, bei, mit, nach, seit, von, zu, gegenüber → her zaman Dativ. Kısaltmalar: zum (zu+dem), zur (zu+der), vom (von+dem), beim (bei+dem).",
        examples: [
          { de: "Ich komme aus der Türkei.", tr: "Türkiye'den geliyorum." },
          { de: "Ich gehe zum Arzt.", tr: "Doktora gidiyorum." },
          { de: "Ich bin seit einer Woche hier.", tr: "Bir haftadır buradayım." },
        ],
      },
      {
        heading: "Dativ Gerektiren Fiiller",
        body: "helfen, gefallen, gehören, danken, glauben, antworten, folgen → Dativ nesne alır: Das gefällt mir. Er hilft mir.",
        examples: [
          { de: "Das gefällt mir sehr.", tr: "Bu bana çok hoş geliyor." },
          { de: "Er hilft seiner Schwester.", tr: "Kız kardeşine yardım ediyor." },
          { de: "Das gehört meinem Vater.", tr: "Bu babama ait." },
        ],
      },
    ],
    exercises: {
      multipleChoice: [
        {
          id: 1,
          question: "Ich fahre mit ___ Bus.",
          options: ["der", "dem", "den", "das"],
          correct: 1,
          explanation: "Bus = maskulin; mit → Dativ → dem.",
        },
        {
          id: 2,
          question: "Sie kommt aus ___ Türkei.",
          options: ["dem", "den", "der", "die"],
          correct: 2,
          explanation: "Türkei = feminin; aus → Dativ → der.",
        },
        {
          id: 3,
          question: "Das Buch gehört ___ Kind.",
          options: ["das", "den", "der", "dem"],
          correct: 3,
          explanation: "Kind = nötr; gehören → Dativ → dem.",
        },
        {
          id: 4,
          question: "Er wohnt bei ___ Eltern.",
          options: ["die", "den", "dem", "der"],
          correct: 1,
          explanation: "Eltern = plural; bei → Dativ → den.",
        },
        {
          id: 5,
          question: "Ich danke ___ Lehrerin.",
          options: ["die", "der", "dem", "den"],
          correct: 1,
          explanation: "Lehrerin = feminin; danken → Dativ → der.",
        },
        {
          id: 6,
          question: "Das gefällt ___.",
          options: ["ich", "mich", "mir", "mein"],
          correct: 2,
          explanation: "gefallen → Dativ; ich → Dativ → mir.",
        },
        {
          id: 7,
          question: "Seit ___ Woche lerne ich Deutsch.",
          options: ["die", "der", "dem", "einer"],
          correct: 3,
          explanation: "Woche = feminin; seit → Dativ; belirsiz → einer.",
        },
        {
          id: 8,
          question: "Ich gehe zu ___ Arzt.",
          options: ["den", "der", "dem", "das"],
          correct: 2,
          explanation: "Arzt = maskulin; zu → Dativ → dem; zu+dem = zum.",
        },
      ],
      fillInBlank: [
        {
          id: 1,
          before: "Er hilft",
          after: "Schwester.",
          answer: "seiner",
          hint: "helfen → Dativ; Schwester feminin → seiner",
        },
        {
          id: 2,
          before: "Wir kommen aus",
          after: "Stadt.",
          answer: "der",
          hint: "Stadt = feminin; aus → Dativ → der",
        },
        {
          id: 3,
          before: "Das Spielzeug gehört",
          after: "Kind.",
          answer: "dem",
          hint: "Kind = nötr; gehören → Dativ → dem",
        },
        {
          id: 4,
          before: "Ich fahre mit",
          after: "Zug.",
          answer: "dem",
          hint: "Zug = maskulin; mit → Dativ → dem",
        },
        {
          id: 5,
          before: "Sie antwortet",
          after: "Lehrer.",
          answer: "dem",
          hint: "antworten → Dativ; Lehrer = maskulin → dem",
        },
      ],
    },
  },
  {
    id: "a2-wechselpraepositionen",
    title: "Wechselpräpositionen",
    subtitle: "İki Hallı Edatlar: Akkusativ ve Dativ",
    explanation: "an, auf, hinter, in, neben, über, unter, vor, zwischen → hareket (wohin? → Akkusativ) veya konum (wo? → Dativ) göre değişir.",
    rules: [
      {
        heading: "Wohin? → Akkusativ / Wo? → Dativ",
        body: "Hareket/yön (wohin?): Ich lege das Buch auf den Tisch. (Akkusativ) | Konum/yer (wo?): Das Buch liegt auf dem Tisch. (Dativ).",
        examples: [
          { de: "Ich lege das Buch auf den Tisch. (wohin?)", tr: "Kitabı masanın üstüne koyuyorum." },
          { de: "Das Buch liegt auf dem Tisch. (wo?)", tr: "Kitap masanın üstünde duruyor." },
          { de: "Er hängt das Bild an die Wand. (wohin?)", tr: "Resmi duvara asıyor." },
        ],
      },
      {
        heading: "Birleşik Formlar",
        body: "im = in+dem (wo?), ins = in+das (wohin?), am = an+dem (wo?), ans = an+das (wohin?), aufs = auf+das (wohin?). Örnek: Wir gehen ins Kino. Er sitzt im Kino.",
        examples: [
          { de: "Wir gehen ins Kino. (wohin?)", tr: "Sinemaya gidiyoruz." },
          { de: "Wir sitzen im Kino. (wo?)", tr: "Sinemada oturuyoruz." },
          { de: "Er geht ans Fenster. (wohin?)", tr: "Pencereye gidiyor." },
        ],
      },
    ],
    exercises: {
      multipleChoice: [
        {
          id: 1,
          question: "Das Buch liegt auf ___ Tisch. (wo?)",
          options: ["den", "dem", "das", "die"],
          correct: 1,
          explanation: "wo? → Dativ; Tisch = maskulin → dem.",
        },
        {
          id: 2,
          question: "Ich lege das Buch auf ___ Tisch. (wohin?)",
          options: ["dem", "das", "den", "der"],
          correct: 2,
          explanation: "wohin? → Akkusativ; Tisch = maskulin → den.",
        },
        {
          id: 3,
          question: "Er hängt das Bild an ___ Wand. (wohin?)",
          options: ["der", "dem", "die", "den"],
          correct: 2,
          explanation: "wohin? → Akkusativ; Wand = feminin → die.",
        },
        {
          id: 4,
          question: "Das Bild hängt an ___ Wand. (wo?)",
          options: ["die", "den", "dem", "der"],
          correct: 3,
          explanation: "wo? → Dativ; Wand = feminin → der.",
        },
        {
          id: 5,
          question: "Wir gehen ___ Kino.",
          options: ["im", "ins", "in dem", "in der"],
          correct: 1,
          explanation: "gehen = hareket, wohin? → in+das = ins.",
        },
        {
          id: 6,
          question: "Er sitzt ___ Büro.",
          options: ["ins", "in das", "im", "in den"],
          correct: 2,
          explanation: "sitzen = konum, wo? → in+dem = im.",
        },
        {
          id: 7,
          question: "Die Katze sitzt ___ Sofa. (auf, wo?)",
          options: ["auf den", "auf das", "auf dem", "auf der"],
          correct: 2,
          explanation: "sitzen = konum, wo? → Dativ; Sofa = nötr → auf dem.",
        },
        {
          id: 8,
          question: "Stell die Vase ___ Tisch. (neben, wohin?)",
          options: ["neben dem", "neben der", "neben den", "neben das"],
          correct: 2,
          explanation: "wohin? → Akkusativ; Tisch = maskulin → neben den.",
        },
      ],
      fillInBlank: [
        {
          id: 1,
          before: "Die Lampe hängt",
          after: "Tisch. (über, wo?)",
          answer: "über dem",
          hint: "wo? → Dativ; Tisch maskulin → über dem",
        },
        {
          id: 2,
          before: "Er stellt die Lampe",
          after: "Tisch. (auf, wohin?)",
          answer: "auf den",
          hint: "wohin? → Akkusativ; Tisch maskulin → auf den",
        },
        {
          id: 3,
          before: "Wir essen",
          after: "Restaurant.",
          answer: "im",
          hint: "essen = konum → wo? → in+dem = im",
        },
        {
          id: 4,
          before: "Das Kind schläft",
          after: "Bett. (in, wo?)",
          answer: "im",
          hint: "Bett = nötr; wo? → in+dem = im",
        },
        {
          id: 5,
          before: "Sie legt die Jacke",
          after: "Stuhl. (auf, wohin?)",
          answer: "auf den",
          hint: "wohin? → Akkusativ; Stuhl maskulin → auf den",
        },
      ],
    },
  },
  {
    id: "a2-komparativ-superlativ",
    title: "Komparativ & Superlativ",
    subtitle: "Karşılaştırma ve En Üstünlük",
    explanation: "Komparativ (-er) karşılaştırır, Superlativ (am …-sten / -sten) en üstünlük belirtir. Bazı sıfatlar Umlaut alır.",
    rules: [
      {
        heading: "Komparativ: Adjektif + -er",
        body: "schnell→schneller, billig→billiger. Kısa tek heceli sıfatlarda Umlaut: alt→älter, jung→jünger, groß→größer. Karşılaştırma: A ist … -er als B.",
        examples: [
          { de: "Berlin ist größer als München.", tr: "Berlin, Münih'ten büyüktür." },
          { de: "Er ist jünger als ich.", tr: "O benden gençtir." },
          { de: "Das ist billiger als das andere.", tr: "Bu diğerinden daha ucuz." },
        ],
      },
      {
        heading: "Superlativ: am …-sten / -sten",
        body: "Yüklemde: am schnellsten. İsim önünde: der/die/das …-ste. -d/-t/-s/-sch/-z biter → -esten: am interessantesten.",
        examples: [
          { de: "Er läuft am schnellsten.", tr: "En hızlı o koşuyor." },
          { de: "Das ist das beste Restaurant.", tr: "Bu en iyi restoran." },
          { de: "das interessanteste Buch", tr: "en ilginç kitap" },
        ],
      },
      {
        heading: "Düzensiz Formlar",
        body: "gut → besser → am besten | viel → mehr → am meisten | gern → lieber → am liebsten | hoch → höher → am höchsten | nah → näher → am nächsten.",
        examples: [
          { de: "Er spricht besser als ich.", tr: "O benden daha iyi konuşuyor." },
          { de: "Ich esse am liebsten Pizza.", tr: "En çok pizzayı severim." },
          { de: "Sie hat mehr Zeit als er.", tr: "Onun daha fazla zamanı var." },
        ],
        table: {
          headers: ["Sıfat", "Komparativ", "Superlativ"],
          rows: [
            ["gut", "besser", "am besten"],
            ["viel", "mehr", "am meisten"],
            ["gern", "lieber", "am liebsten"],
            ["hoch", "höher", "am höchsten"],
            ["nah", "näher", "am nächsten"],
          ],
        },
      },
    ],
    exercises: {
      multipleChoice: [
        {
          id: 1,
          question: "Berlin ist ___ als meine Stadt. (groß)",
          options: ["großer", "größer", "am größten", "größten"],
          correct: 1,
          explanation: "Komparativ: groß → größer (Umlaut + -er).",
        },
        {
          id: 2,
          question: "Er spricht ___ als ich. (gut)",
          options: ["gut", "gutem", "besser", "am besten"],
          correct: 2,
          explanation: "gut düzensiz: Komparativ → besser.",
        },
        {
          id: 3,
          question: "Das ist das ___ Restaurant in der Stadt. (gut)",
          options: ["bessere", "beste", "bestes", "gut"],
          correct: 1,
          explanation: "İsim önünde superlativ: das beste.",
        },
        {
          id: 4,
          question: "Er läuft am ___. (schnell)",
          options: ["schnellsten", "schnellste", "schneller", "schnellst"],
          correct: 0,
          explanation: "am + -sten → am schnellsten.",
        },
        {
          id: 5,
          question: "Ich esse ___ Pizza. (gern → Superlativ)",
          options: ["am gernsten", "am liebsten", "am liebersten", "lieber"],
          correct: 1,
          explanation: "gern düzensiz: Superlativ → am liebsten.",
        },
        {
          id: 6,
          question: "Mein Bruder ist ___ als ich. (jung)",
          options: ["jünger", "jungerer", "am jüngsten", "junger"],
          correct: 0,
          explanation: "jung → jünger (Umlaut + -er).",
        },
        {
          id: 7,
          question: "Sie hat ___ Bücher als er. (viel)",
          options: ["viele", "mehrere", "mehr", "meiste"],
          correct: 2,
          explanation: "viel düzensiz: Komparativ → mehr.",
        },
        {
          id: 8,
          question: "Das ist die ___ Aufgabe. (schwer)",
          options: ["schwerste", "schwerer", "am schwersten", "schwersten"],
          correct: 0,
          explanation: "İsim önünde superlativ: die schwerste.",
        },
      ],
      fillInBlank: [
        {
          id: 1,
          before: "Dieses Auto ist",
          after: "als jenes. (teuer)",
          answer: "teurer",
          hint: "teuer → teurer (e düşer: teur+er)",
        },
        {
          id: 2,
          before: "Er wohnt am",
          after: "von uns allen. (nah)",
          answer: "nächsten",
          hint: "nah → näher → am nächsten (düzensiz)",
        },
        {
          id: 3,
          before: "Sie spricht",
          after: "als ich. (viel)",
          answer: "mehr",
          hint: "viel → mehr (düzensiz komparativ)",
        },
        {
          id: 4,
          before: "Das ist das",
          after: "Buch, das ich je gelesen habe. (interessant)",
          answer: "interessanteste",
          hint: "-t biter → -este: interessanteste",
        },
        {
          id: 5,
          before: "Meine Oma ist",
          after: "als mein Opa. (alt)",
          answer: "älter",
          hint: "alt → älter (Umlaut)",
        },
      ],
    },
  },
  {
    id: "a2-reflexivverben",
    title: "Reflexivverben",
    subtitle: "Dönüşlü Fiiller",
    explanation: "Reflexivverben (dönüşlü fiiller) öznesi ve nesnesi aynı kişi olan fiillerdir. Reflexivpronomen öznesiyle uyuşur.",
    rules: [
      {
        heading: "Akkusativ Reflexivpronomen",
        body: "ich→mich | du→dich | er/sie/es→sich | wir→uns | ihr→euch | sie/Sie→sich. Fiil doğrudan bir nesne almadığında kullanılır.",
        examples: [
          { de: "Ich wasche mich.", tr: "Yıkanıyorum." },
          { de: "Du kämmst dich.", tr: "Saçını tarıyorsun." },
          { de: "Er freut sich.", tr: "Seviniyor." },
        ],
        table: {
          headers: ["Şahıs", "Akkusativ Refl."],
          rows: [
            ["ich", "mich"],
            ["du", "dich"],
            ["er/sie/es", "sich"],
            ["wir", "uns"],
            ["ihr", "euch"],
            ["sie/Sie", "sich"],
          ],
        },
      },
      {
        heading: "Dativ Reflexiv (İki Nesne)",
        body: "Fiil hem refleksif hem Akkusativ nesne aldığında refleksif nesne Dativ olur: ich→mir, du→dir, diğerleri aynı. Ich wasche mir die Hände.",
        examples: [
          { de: "Ich wasche mir die Hände.", tr: "Ellerimi yıkıyorum." },
          { de: "Du putzt dir die Zähne.", tr: "Dişlerini fırçalıyorsun." },
          { de: "Er kämmt sich die Haare.", tr: "Saçını tarıyor." },
        ],
      },
    ],
    exercises: {
      multipleChoice: [
        {
          id: 1,
          question: "Ich freue ___ auf den Urlaub.",
          options: ["mich", "mir", "sich", "dich"],
          correct: 0,
          explanation: "ich → Akkusativ refleksif → mich.",
        },
        {
          id: 2,
          question: "Er zieht ___ schnell an.",
          options: ["mich", "sich", "dich", "euch"],
          correct: 1,
          explanation: "er → refleksif → sich.",
        },
        {
          id: 3,
          question: "Wir setzen ___ ans Fenster.",
          options: ["sich", "euch", "uns", "mich"],
          correct: 2,
          explanation: "wir → refleksif → uns.",
        },
        {
          id: 4,
          question: "Ich wasche ___ die Hände. (Dativ)",
          options: ["mich", "mir", "sich", "dich"],
          correct: 1,
          explanation: "İki nesne var → refleksif Dativ → mir.",
        },
        {
          id: 5,
          question: "Du erinnerst ___ an den Film?",
          options: ["sich", "mir", "dich", "dir"],
          correct: 2,
          explanation: "du → Akkusativ refleksif → dich.",
        },
        {
          id: 6,
          question: "Ihr interessiert ___ für Sport.",
          options: ["euch", "uns", "sich", "mich"],
          correct: 0,
          explanation: "ihr → refleksif → euch.",
        },
        {
          id: 7,
          question: "Sie fühlt ___ heute nicht gut.",
          options: ["mich", "sich", "ihr", "dich"],
          correct: 1,
          explanation: "sie (tekil) → refleksif → sich.",
        },
        {
          id: 8,
          question: "Ich stelle ___ vor. (tanıtmak)",
          options: ["mir", "mich", "sich", "dich"],
          correct: 1,
          explanation: "vorstellen (tanıtmak) → Akkusativ refleksif → mich.",
        },
      ],
      fillInBlank: [
        {
          id: 1,
          before: "Er ärgert",
          after: "über den Stau.",
          answer: "sich",
          hint: "er → refleksif → sich",
        },
        {
          id: 2,
          before: "Ich kämme",
          after: "die Haare. (Dativ)",
          answer: "mir",
          hint: "İki nesne: Haare Akkusativ → refleksif Dativ → mir",
        },
        {
          id: 3,
          before: "Wir treffen",
          after: "um 3 Uhr.",
          answer: "uns",
          hint: "wir → refleksif → uns",
        },
        {
          id: 4,
          before: "Du kannst",
          after: "auf mich verlassen.",
          answer: "dich",
          hint: "du → Akkusativ refleksif → dich",
        },
        {
          id: 5,
          before: "Sie haben",
          after: "für das Projekt gemeldet.",
          answer: "sich",
          hint: "sie (çoğul) → refleksif → sich",
        },
      ],
    },
  },
  {
    id: "a2-nebensaetze-weil-dass",
    title: "Nebensätze: weil & dass",
    subtitle: "Neden ve Dolaylı Anlatım Yan Cümleleri",
    explanation: "Nebensatz (yan cümle) bir bağlaçla başlar ve fiili sona taşır. 'weil' neden bildirir, 'dass' dolaylı anlatım için kullanılır.",
    rules: [
      {
        heading: "Nebensatz Yapısı",
        body: "Bağlaç + Özne + ... + Fiil (sona). Ana cümleyle araya virgül girer. Modalverb varsa: İnfinitiv + Modal (her ikisi sona).",
        examples: [
          { de: "Ich lerne Deutsch, weil es interessant ist.", tr: "Almanca öğreniyorum çünkü ilginç." },
          { de: "Er bleibt zu Hause, weil er krank ist.", tr: "Hasta olduğu için evde kalıyor." },
          { de: "Sie lernt, weil sie die Prüfung bestehen möchte.", tr: "Sınavı geçmek istediği için çalışıyor." },
        ],
      },
      {
        heading: "weil — Neden/Gerekçe",
        body: "'weil' soru kelimesi 'warum?' sorusunu cevaplar. Fiil her zaman sona gider. Cümle başında ise ana cümle fiili öne geçer: Weil er krank ist, bleibt er zu Hause.",
        examples: [
          { de: "Warum lernst du Deutsch? — Weil ich in Deutschland arbeiten möchte.", tr: "Neden Almanca öğreniyorsun? — Almanya'da çalışmak istediğim için." },
          { de: "Weil es regnet, bleiben wir zu Hause.", tr: "Yağmur yağdığı için evde kalıyoruz." },
          { de: "Er ist müde, weil er lange gearbeitet hat.", tr: "Uzun çalıştığı için yorgun." },
        ],
      },
      {
        heading: "dass — Dolaylı Anlatım",
        body: "'dass' genellikle 'sagen, denken, glauben, wissen, hoffen' gibi fiillerden sonra gelir. Fiil sona gider.",
        examples: [
          { de: "Ich denke, dass du Recht hast.", tr: "Haklı olduğunu düşünüyorum." },
          { de: "Er sagt, dass er müde ist.", tr: "Yorgun olduğunu söylüyor." },
          { de: "Ich weiß, dass sie kommt.", tr: "Onun geleceğini biliyorum." },
        ],
      },
    ],
    exercises: {
      multipleChoice: [
        {
          id: 1,
          question: "Ich gehe schlafen, weil ich müde ___.",
          options: ["bin ich", "ich bin", "bin", "ist"],
          correct: 2,
          explanation: "weil → Verbletzte: fiil sona → bin.",
        },
        {
          id: 2,
          question: "Er sagt, ___ er morgen kommt.",
          options: ["weil", "ob", "dass", "wenn"],
          correct: 2,
          explanation: "dolaylı anlatım (sagen) → dass.",
        },
        {
          id: 3,
          question: "Sie lernt Deutsch, weil sie in Berlin ___ möchte.",
          options: ["wohnen", "wohnt", "wohnen sie", "wohne"],
          correct: 0,
          explanation: "weil → İnfinitiv Modal sona: wohnen möchte.",
        },
        {
          id: 4,
          question: "Ich hoffe, dass du bald ___ kommst.",
          options: ["nach Hause kommst", "kommst nach Hause", "nach Hause", "kommt"],
          correct: 0,
          explanation: "dass → fiil sona; du → kommst: nach Hause kommst.",
        },
        {
          id: 5,
          question: "Wir bleiben zu Hause, weil es draußen kalt ___.",
          options: ["es ist", "ist", "ist es", "sein"],
          correct: 1,
          explanation: "weil → Verbletzte → ist sona.",
        },
        {
          id: 6,
          question: "Ich glaube, ___ er recht hat.",
          options: ["weil", "dass", "ob", "denn"],
          correct: 1,
          explanation: "glauben + dolaylı anlatım → dass.",
        },
        {
          id: 7,
          question: "Er bleibt zu Hause, weil er krank ___.",
          options: ["er ist", "ist er", "ist", "sein"],
          correct: 2,
          explanation: "weil → Verbletzte → ist.",
        },
        {
          id: 8,
          question: "Sie weiß, dass du ___ lügst.",
          options: ["sie", "du", "ihn", "ihr"],
          correct: 1,
          explanation: "dass-Satz'da özne değişmez: dass du lügst.",
        },
      ],
      fillInBlank: [
        {
          id: 1,
          before: "Ich bleibe zu Hause,",
          after: "es regnet.",
          answer: "weil",
          hint: "neden → weil",
        },
        {
          id: 2,
          before: "Er weiß, dass sie heute nicht",
          after: ".",
          answer: "kommt",
          hint: "dass → fiil sona; sie → kommt",
        },
        {
          id: 3,
          before: "Wir lernen Deutsch,",
          after: "wir nach Deutschland reisen möchten.",
          answer: "weil",
          hint: "çünkü → weil",
        },
        {
          id: 4,
          before: "Ich denke,",
          after: "das richtig ist.",
          answer: "dass",
          hint: "denken + dolaylı anlatım → dass",
        },
        {
          id: 5,
          before: "Er ist müde,",
          after: "er lange gearbeitet hat.",
          answer: "weil",
          hint: "neden/gerekçe → weil",
        },
      ],
    },
  },
  {
    id: "a2-nebensaetze-wenn-ob",
    title: "Nebensätze: wenn & ob",
    subtitle: "Koşul ve Dolaylı Soru Yan Cümleleri",
    explanation: "'wenn' koşul veya tekrar eden durum bildirir. 'ob' evet/hayır dolaylı sorusu için kullanılır. Her ikisinde de fiil sona gider.",
    rules: [
      {
        heading: "wenn — Koşul / Tekrar",
        body: "Wenn ich Zeit habe, komme ich. Wenn başta olunca ana cümle fiili öne geçer. als: geçmişte tek olay için; wenn: şimdi/gelecek veya tekrar eden geçmiş.",
        examples: [
          { de: "Wenn es regnet, bleibe ich zu Hause.", tr: "Yağmur yağarsa evde kalırım." },
          { de: "Ich komme, wenn ich fertig bin.", tr: "Hazır olunca gelirim." },
          { de: "Wenn ich als Kind Schokolade aß, war ich glücklich.", tr: "Çocukken çikolata yediğimde mutlu olurdum." },
        ],
      },
      {
        heading: "ob — Dolaylı Evet/Hayır Sorusu",
        body: "Direkt soru 'Kommt er?' → dolaylı: 'Ich weiß nicht, ob er kommt.' Filler: wissen, fragen, sich fragen, nicht sicher sein + ob.",
        examples: [
          { de: "Ich weiß nicht, ob er kommt.", tr: "Gelip gelmeyeceğini bilmiyorum." },
          { de: "Sie fragt, ob das Geschäft geöffnet ist.", tr: "Dükkanın açık olup olmadığını soruyor." },
          { de: "Ich bin nicht sicher, ob ich kommen kann.", tr: "Gelip gelemeyeceğimden emin değilim." },
        ],
      },
      {
        heading: "wenn vs. als",
        body: "wenn: şimdiki/gelecek zaman veya geçmişte tekrar eden olaylar. als: geçmişte tek, belirli bir olayı anlatır.",
        examples: [
          { de: "Als ich jung war, lebte ich in Ankara. (tek olay)", tr: "Gençken Ankara'da yaşadım." },
          { de: "Wenn ich jung war, spielte ich draußen. (her seferinde)", tr: "Gençken hep dışarıda oynardım." },
          { de: "Als er ankam, waren wir schon da.", tr: "O geldiğinde biz zaten oradaydık." },
        ],
      },
    ],
    exercises: {
      multipleChoice: [
        {
          id: 1,
          question: "___ es morgen regnet, bleiben wir zu Hause.",
          options: ["Weil", "Dass", "Wenn", "Ob"],
          correct: 2,
          explanation: "Koşul (eğer) → wenn.",
        },
        {
          id: 2,
          question: "Ich weiß nicht, ___ er kommt.",
          options: ["wenn", "dass", "weil", "ob"],
          correct: 3,
          explanation: "Dolaylı evet/hayır sorusu → ob.",
        },
        {
          id: 3,
          question: "___ ich klein war, spielte ich viel. (Geçmişte tek dönem)",
          options: ["Wenn", "Ob", "Als", "Weil"],
          correct: 2,
          explanation: "Geçmişte tek bir dönem → als.",
        },
        {
          id: 4,
          question: "Wenn du Zeit ___, ruf mich an.",
          options: ["hast", "haben", "hat", "habt"],
          correct: 0,
          explanation: "wenn → Verbletzte; du → hast.",
        },
        {
          id: 5,
          question: "Sie fragt, ___ das Restaurant geöffnet ist.",
          options: ["wenn", "weil", "dass", "ob"],
          correct: 3,
          explanation: "fragen + dolaylı soru → ob.",
        },
        {
          id: 6,
          question: "Ich komme, ___ ich fertig bin.",
          options: ["ob", "als", "wenn", "weil"],
          correct: 2,
          explanation: "Koşul cümle içindeyse → wenn.",
        },
        {
          id: 7,
          question: "___ ich die Prüfung bestehe, feiere ich.",
          options: ["Ob", "Weil", "Als", "Wenn"],
          correct: 3,
          explanation: "Koşul (eğer geçersem) → wenn.",
        },
        {
          id: 8,
          question: "Er weiß nicht, ___ sie glücklich ist.",
          options: ["wenn", "weil", "ob", "dass"],
          correct: 2,
          explanation: "bilmeme + evet/hayır belirsizliği → ob.",
        },
      ],
      fillInBlank: [
        {
          id: 1,
          before: "Ich frage mich,",
          after: "das stimmt.",
          answer: "ob",
          hint: "evet/hayır belirsizliği → ob",
        },
        {
          id: 2,
          before: "",
          after: "du müde bist, schlaf ein bisschen.",
          answer: "Wenn",
          hint: "Koşul, cümle başında → Wenn",
        },
        {
          id: 3,
          before: "Wir spielten draußen,",
          after: "das Wetter gut war. (her seferinde)",
          answer: "wenn",
          hint: "tekrar eden geçmiş → wenn",
        },
        {
          id: 4,
          before: "Er weiß nicht,",
          after: "er die Prüfung bestanden hat.",
          answer: "ob",
          hint: "dolaylı evet/hayır sorusu → ob",
        },
        {
          id: 5,
          before: "",
          after: "ich jung war, wohnte ich auf dem Land.",
          answer: "Als",
          hint: "geçmişte tek bir dönem → Als",
        },
      ],
    },
  },
  {
    id: "a2-futur1",
    title: "Futur I",
    subtitle: "Gelecek Zaman",
    explanation: "Futur I = werden (çekimli) + İnfinitiv. Gelecekteki planlar, tahminler ve söz vermek için kullanılır.",
    rules: [
      {
        heading: "werden Çekimi",
        body: "ich werde, du wirst, er/sie/es wird, wir werden, ihr werdet, sie/Sie werden. İnfinitiv cümlenin sonuna gider.",
        examples: [
          { de: "Ich werde morgen arbeiten.", tr: "Yarın çalışacağım." },
          { de: "Er wird kommen.", tr: "O gelecek." },
          { de: "Es wird regnen.", tr: "Yağmur yağacak. (tahmin)" },
        ],
        table: {
          headers: ["Şahıs", "werden"],
          rows: [
            ["ich", "werde"],
            ["du", "wirst"],
            ["er/sie/es", "wird"],
            ["wir", "werden"],
            ["ihr", "werdet"],
            ["sie/Sie", "werden"],
          ],
        },
      },
      {
        heading: "Kullanım Alanları",
        body: "1. Gelecek planlar: Ich werde nächste Woche reisen. 2. Tahmin: Es wird regnen. 3. Söz: Ich werde es machen! Günlük konuşmada Präsens + zaman zarfı da yaygın: Ich gehe morgen.",
        examples: [
          { de: "Ich werde nächstes Jahr nach Berlin ziehen.", tr: "Gelecek yıl Berlin'e taşınacağım." },
          { de: "Du wirst das schaffen!", tr: "Bunu başaracaksın! (söz/tahmin)" },
          { de: "Wir werden zusammen lernen.", tr: "Birlikte çalışacağız." },
        ],
      },
    ],
    exercises: {
      multipleChoice: [
        {
          id: 1,
          question: "Er ___ morgen kommen.",
          options: ["wird", "wird sein", "werde", "werdet"],
          correct: 0,
          explanation: "er → wird; İnfinitiv (kommen) sona.",
        },
        {
          id: 2,
          question: "Ich ___ nächstes Jahr nach Deutschland fahren.",
          options: ["wirst", "werde", "wird", "werden"],
          correct: 1,
          explanation: "ich → werde.",
        },
        {
          id: 3,
          question: "Wir ___ das Problem lösen.",
          options: ["wird", "werde", "werdet", "werden"],
          correct: 3,
          explanation: "wir → werden.",
        },
        {
          id: 4,
          question: "Es ___ heute Abend regnen.",
          options: ["werden", "werde", "wirst", "wird"],
          correct: 3,
          explanation: "es → wird (tahmin).",
        },
        {
          id: 5,
          question: "Ihr ___ die Aufgabe bis Freitag fertigmachen.",
          options: ["wird", "werde", "werden", "werdet"],
          correct: 3,
          explanation: "ihr → werdet.",
        },
        {
          id: 6,
          question: "Du ___ das nicht vergessen!",
          options: ["werde", "wird", "wirst", "werden"],
          correct: 2,
          explanation: "du → wirst.",
        },
        {
          id: 7,
          question: "Sie (Pl.) ___ bald zurückkommen.",
          options: ["wird", "werde", "werdet", "werden"],
          correct: 3,
          explanation: "sie (çoğul) → werden.",
        },
        {
          id: 8,
          question: "Ich glaube, es ___ morgen schneien.",
          options: ["werde", "werden", "wirst", "wird"],
          correct: 3,
          explanation: "es → wird (tahmin).",
        },
      ],
      fillInBlank: [
        {
          id: 1,
          before: "Du",
          after: "den Test bestehen.",
          answer: "wirst",
          hint: "du → wirst",
        },
        {
          id: 2,
          before: "Wir",
          after: "nächsten Sommer reisen.",
          answer: "werden",
          hint: "wir → werden",
        },
        {
          id: 3,
          before: "Ich",
          after: "dir helfen.",
          answer: "werde",
          hint: "ich → werde",
        },
        {
          id: 4,
          before: "Er",
          after: "die Arbeit bis morgen fertig machen.",
          answer: "wird",
          hint: "er → wird",
        },
        {
          id: 5,
          before: "Ihr",
          after: "Deutsch lernen.",
          answer: "werdet",
          hint: "ihr → werdet",
        },
      ],
    },
  },
  {
    id: "a2-modalverben-praeteritum",
    title: "Modalverben im Präteritum",
    subtitle: "Kiplik Fiillerin Geçmiş Zaman Formu",
    explanation: "Modalverben geçmişte her zaman Präteritum ile kullanılır (Perfekt değil). Umlaut düşer, -te eklenir.",
    rules: [
      {
        heading: "Modalverben Präteritum Tablosu",
        body: "können→konnte | müssen→musste | wollen→wollte | dürfen→durfte | sollen→sollte | mögen→mochte. ich/er/sie/es formu aynıdır: ich konnte = er konnte.",
        examples: [
          { de: "Ich konnte nicht schlafen.", tr: "Uyuyamadım." },
          { de: "Er musste früh aufstehen.", tr: "Erken kalkmak zorundaydı." },
          { de: "Sie wollte nach Paris fahren.", tr: "Paris'e gitmek istiyordu." },
        ],
        table: {
          headers: ["Modal", "Präteritum", "ich/er"],
          rows: [
            ["können", "konnte", "ich/er konnte"],
            ["müssen", "musste", "ich/er musste"],
            ["wollen", "wollte", "ich/er wollte"],
            ["dürfen", "durfte", "ich/er durfte"],
            ["sollen", "sollte", "ich/er sollte"],
            ["mögen", "mochte", "ich/er mochte"],
          ],
        },
      },
      {
        heading: "Çekim Ekleri",
        body: "ich/er/sie/es: -e (konnte) | du: -est (konntest) | wir/sie/Sie: -en (konnten) | ihr: -et (konntet). İnfinitiv cümlenin sonuna gider.",
        examples: [
          { de: "Wir durften dort nicht parken.", tr: "Orada park edemezdik." },
          { de: "Du solltest das nicht sagen.", tr: "Bunu söylememen gerekirdi." },
          { de: "Sie mussten lange warten.", tr: "Uzun süre beklemek zorunda kaldılar." },
        ],
      },
    ],
    exercises: {
      multipleChoice: [
        {
          id: 1,
          question: "Ich ___ gestern nicht schlafen. (können)",
          options: ["konnte", "könnte", "kann", "konnt"],
          correct: 0,
          explanation: "können Präteritum → konnte; ich → konnte.",
        },
        {
          id: 2,
          question: "Er ___ früh aufstehen. (müssen)",
          options: ["muss", "musste", "müsste", "musst"],
          correct: 1,
          explanation: "müssen Präteritum → musste; er → musste.",
        },
        {
          id: 3,
          question: "Sie ___ als Kind kein Eis essen. (dürfen)",
          options: ["darf", "durfte", "dürfte", "durft"],
          correct: 1,
          explanation: "dürfen Präteritum → durfte; sie (tekil) → durfte.",
        },
        {
          id: 4,
          question: "Wir ___ das Museum besuchen. (wollen)",
          options: ["wollten", "wollte", "wolltest", "wollen"],
          correct: 0,
          explanation: "wollen Präteritum → wollte; wir → wollten.",
        },
        {
          id: 5,
          question: "Du ___ das Formular ausfüllen. (sollen)",
          options: ["soll", "solltest", "sollte", "sollt"],
          correct: 1,
          explanation: "sollen Präteritum → sollte; du → solltest.",
        },
        {
          id: 6,
          question: "Er ___ Schokolade nicht. (mögen, Präteritum)",
          options: ["mochte", "möchte", "mag", "gemocht"],
          correct: 0,
          explanation: "mögen Präteritum → mochte; Umlaut düşer.",
        },
        {
          id: 7,
          question: "Ich ___ drei Sprachen sprechen. (können)",
          options: ["konnte", "könnte", "kann", "gekonnt"],
          correct: 0,
          explanation: "können → konnte; ich → konnte.",
        },
        {
          id: 8,
          question: "Sie (Pl.) ___ die Hausaufgaben machen. (müssen)",
          options: ["musste", "müssten", "mussten", "müssen"],
          correct: 2,
          explanation: "müssen → musste; sie (çoğul) → mussten.",
        },
      ],
      fillInBlank: [
        {
          id: 1,
          before: "Ich",
          after: "gestern lange warten. (müssen)",
          answer: "musste",
          hint: "müssen → musste; ich → musste",
        },
        {
          id: 2,
          before: "Er",
          after: "nicht kommen. (können)",
          answer: "konnte",
          hint: "können → konnte; er → konnte",
        },
        {
          id: 3,
          before: "Wir",
          after: "dort nicht parken. (dürfen)",
          answer: "durften",
          hint: "dürfen → durfte; wir → durften",
        },
        {
          id: 4,
          before: "Du",
          after: "das nicht sagen. (sollen)",
          answer: "solltest",
          hint: "sollen → sollte; du → solltest",
        },
        {
          id: 5,
          before: "Sie",
          after: "nach Hause gehen. (wollen, tekil)",
          answer: "wollte",
          hint: "wollen → wollte; sie (tekil) → wollte",
        },
      ],
    },
  },
  {
    id: "a2-adjektivdeklination",
    title: "Adjektivdeklination (ohne Artikel)",
    subtitle: "Artikelsiz Sıfat Çekimi",
    explanation: "Artikel olmadığında sıfat kendi başına durum bilgisi taşır (güçlü çekim). Maskulin Nom: -er, Feminin Nom: -e, Nötr Nom/Akk: -es.",
    rules: [
      {
        heading: "Güçlü Çekim (Artikelsiz)",
        body: "Maskulin: Nom -er, Akk -en, Dat -em | Feminin: Nom/Akk -e, Dat -er | Nötr: Nom/Akk -es, Dat -em | Plural: Nom/Akk -e, Dat -en.",
        examples: [
          { de: "Kalter Kaffee schmeckt nicht.", tr: "Soğuk kahve iyi tatmaz. (mask. Nom)" },
          { de: "Ich trinke gern kalten Kaffee. (mask. Akk)", tr: "Soğuk kahve içmeyi severim." },
          { de: "Frisches Brot ist lecker. (nötr Nom)", tr: "Taze ekmek lezzetli." },
        ],
        table: {
          headers: ["Kasus", "Mask.", "Fem.", "Nötr", "Plural"],
          rows: [
            ["Nominativ", "-er", "-e", "-es", "-e"],
            ["Akkusativ", "-en", "-e", "-es", "-e"],
            ["Dativ", "-em", "-er", "-em", "-en"],
          ],
        },
      },
      {
        heading: "Kullanım Durumları",
        body: "Belirsiz miktar ifadeler, yiyecek/içecek adları, malzeme adları, resmi metinler: ein Glas kalter Milch, ein Stück frisches Brot.",
        examples: [
          { de: "Ein Glas kalter Milch.", tr: "Bir bardak soğuk süt. (fem. Gen)" },
          { de: "Mit frischem Brot.", tr: "Taze ekmekle. (nötr Dat)" },
          { de: "Für gute Freunde.", tr: "İyi arkadaşlar için. (Plural Akk)" },
        ],
      },
    ],
    exercises: {
      multipleChoice: [
        {
          id: 1,
          question: "Ich trinke gern kalt___ Kaffee. (maskulin Akkusativ)",
          options: ["kalter", "kalte", "kalten", "kaltem"],
          correct: 2,
          explanation: "Maskulin Akkusativ artikelsiz → -en.",
        },
        {
          id: 2,
          question: "Das ist frisch___ Brot. (nötr Nominativ)",
          options: ["frischer", "frisches", "frische", "frischen"],
          correct: 1,
          explanation: "Nötr Nominativ artikelsiz → -es.",
        },
        {
          id: 3,
          question: "Er trinkt heiß___ Tee. (maskulin Akkusativ)",
          options: ["heißer", "heißen", "heiße", "heißem"],
          correct: 1,
          explanation: "Maskulin Akkusativ artikelsiz → -en.",
        },
        {
          id: 4,
          question: "Mit gut___ Freunden macht es Spaß. (Plural Dativ)",
          options: ["guten", "guter", "gute", "gutem"],
          correct: 0,
          explanation: "Plural Dativ artikelsiz → -en.",
        },
        {
          id: 5,
          question: "Frisch___ Luft ist gesund. (feminin Nominativ)",
          options: ["frischer", "frischen", "frisches", "frische"],
          correct: 3,
          explanation: "Feminin Nominativ artikelsiz → -e.",
        },
        {
          id: 6,
          question: "Ich esse gern italienisch___ Pasta. (feminin Akkusativ)",
          options: ["italienischer", "italienischen", "italienische", "italienischem"],
          correct: 2,
          explanation: "Feminin Akkusativ artikelsiz → -e.",
        },
        {
          id: 7,
          question: "Das Glas ist aus dünn___ Glas. (nötr Dativ)",
          options: ["dünner", "dünnem", "dünne", "dünnen"],
          correct: 1,
          explanation: "Nötr Dativ artikelsiz → -em.",
        },
        {
          id: 8,
          question: "Alt___ Wein ist teuer. (maskulin Nominativ)",
          options: ["Alten", "Alter", "Alte", "Altem"],
          correct: 1,
          explanation: "Maskulin Nominativ artikelsiz → -er.",
        },
      ],
      fillInBlank: [
        {
          id: 1,
          before: "Ich trinke gern",
          after: "Tee. (heiß, maskulin Akkusativ)",
          answer: "heißen",
          hint: "maskulin Akkusativ artikelsiz → -en",
        },
        {
          id: 2,
          before: "Das ist",
          after: "Fleisch. (frisch, nötr Nominativ)",
          answer: "frisches",
          hint: "nötr Nominativ artikelsiz → -es",
        },
        {
          id: 3,
          before: "Mit",
          after: "Musik lernt man besser. (gut, feminin Dativ)",
          answer: "guter",
          hint: "feminin Dativ artikelsiz → -er",
        },
        {
          id: 4,
          before: "Er mag",
          after: "Wein. (rot, maskulin Akkusativ)",
          answer: "roten",
          hint: "maskulin Akkusativ artikelsiz → -en",
        },
        {
          id: 5,
          before: "Ich liebe",
          after: "Früchte. (frisch, Plural Akkusativ)",
          answer: "frische",
          hint: "Plural Akkusativ artikelsiz → -e",
        },
      ],
    },
  },
  {
    id: "a2-indirekte-fragen",
    title: "Indirekte Fragesätze",
    subtitle: "Dolaylı Soru Cümleleri",
    explanation: "Soru cümlesi başka bir cümlenin içine alındığında 'dolaylı soru' olur. Fiil sona gider. W-sorular için w-sözcüğü, evet/hayır soruları için 'ob' kullanılır.",
    rules: [
      {
        heading: "Dolaylı Soru Yapısı",
        body: "Doğrudan: Wo wohnst du? → Dolaylı: Ich weiß nicht, wo du wohnst. (wohnst sona gider). Doğrudan: Kommt er? → Dolaylı: Ich weiß nicht, ob er kommt.",
        examples: [
          { de: "Wo wohnst du? → Ich weiß nicht, wo du wohnst.", tr: "Nerede yaşıyorsun? → Nerede yaşadığını bilmiyorum." },
          { de: "Kommt er? → Ich frage mich, ob er kommt.", tr: "O geliyor mu? → Gelip gelmeyeceğini merak ediyorum." },
          { de: "Wie viel kostet das? → Kannst du mir sagen, wie viel das kostet?", tr: "Bu ne kadar? → Bunun ne kadar tuttuğunu söyleyebilir misin?" },
        ],
      },
      {
        heading: "Sık Kullanılan Başlangıç İfadeleri",
        body: "Ich weiß nicht, … | Kannst du mir sagen, … | Ich frage mich, … | Ich bin nicht sicher, … | Weißt du, … | Ich verstehe nicht, …",
        examples: [
          { de: "Kannst du mir erklären, wie das funktioniert?", tr: "Bunun nasıl çalıştığını açıklayabilir misin?" },
          { de: "Ich verstehe nicht, warum er so spät kommt.", tr: "Neden bu kadar geç geldiğini anlamıyorum." },
          { de: "Weißt du, wann der Film anfängt?", tr: "Filmin ne zaman başladığını biliyor musun?" },
        ],
      },
    ],
    exercises: {
      multipleChoice: [
        {
          id: 1,
          question: "Ich weiß nicht, ___ er kommt.",
          options: ["wo", "was", "ob", "wer"],
          correct: 2,
          explanation: "Evet/hayır dolaylı sorusu → ob.",
        },
        {
          id: 2,
          question: "Kannst du mir sagen, ___ der Bahnhof ist?",
          options: ["ob", "dass", "wo", "wenn"],
          correct: 2,
          explanation: "Yer sorusu dolaylı → wo.",
        },
        {
          id: 3,
          question: "Ich verstehe nicht, ___ das funktioniert.",
          options: ["ob", "wo", "was", "wie"],
          correct: 3,
          explanation: "Nasıl sorusu → wie.",
        },
        {
          id: 4,
          question: "Sie fragt, ___ das Buch kostet.",
          options: ["ob", "wo", "wie viel", "wann"],
          correct: 2,
          explanation: "Fiyat sorusu dolaylı → wie viel.",
        },
        {
          id: 5,
          question: "Ich frage mich, ___ du so glücklich bist.",
          options: ["ob", "weil", "warum", "dass"],
          correct: 2,
          explanation: "Neden sorusu → warum.",
        },
        {
          id: 6,
          question: "Weißt du, ___ er heißt?",
          options: ["ob", "wie", "was", "wer"],
          correct: 1,
          explanation: "İsim sorusu 'Wie heißt er?' dolaylı → wie.",
        },
        {
          id: 7,
          question: "Ich weiß nicht, ___ er wohnt. Direkt form?",
          options: ["Wo er wohnt?", "Wo wohnt er?", "Er wo wohnt?", "Wohnt er wo?"],
          correct: 1,
          explanation: "Dolaylı: wo er wohnt. Direkt: Wo wohnt er?",
        },
        {
          id: 8,
          question: "Kannst du erklären, ___ wir fahren sollen?",
          options: ["wo", "wohin", "woher", "woran"],
          correct: 1,
          explanation: "Yön sorusu dolaylı → wohin.",
        },
      ],
      fillInBlank: [
        {
          id: 1,
          before: "Ich weiß nicht,",
          after: "er morgen kommt.",
          answer: "ob",
          hint: "evet/hayır sorusu → ob",
        },
        {
          id: 2,
          before: "Kannst du mir sagen,",
          after: "das kostet?",
          answer: "wie viel",
          hint: "fiyat sorusu → wie viel",
        },
        {
          id: 3,
          before: "Ich frage mich,",
          after: "sie so spät schläft.",
          answer: "warum",
          hint: "neden → warum",
        },
        {
          id: 4,
          before: "Weißt du,",
          after: "er wohnt?",
          answer: "wo",
          hint: "yer sorusu → wo",
        },
        {
          id: 5,
          before: "Ich verstehe nicht,",
          after: "das passiert ist.",
          answer: "was",
          hint: "ne sorusu → was",
        },
      ],
    },
  },
  {
    id: "a2-genitiv",
    title: "Genitiv",
    subtitle: "İyelik Hali",
    explanation: "Genitiv (Wessen? — Kimin?), sahiplik ilişkisini gösterir. Maskulin ve nötr isimlere +(e)s eklenir, feminin değişmez.",
    rules: [
      {
        heading: "Genitiv Artikelleri",
        body: "Maskulin: des/eines (isim +(e)s) | Feminin: der/einer | Nötr: des/eines (isim +(e)s) | Plural: der/-.",
        examples: [
          { de: "Das Auto des Mannes ist rot.", tr: "Adamın arabası kırmızı." },
          { de: "Die Tasche der Frau ist teuer.", tr: "Kadının çantası pahalı." },
          { de: "Das Spielzeug des Kindes.", tr: "Çocuğun oyuncağı." },
        ],
        table: {
          headers: ["Genus", "Belirli Genitiv", "İsim Eki"],
          rows: [
            ["Maskulin", "des", "+(e)s"],
            ["Feminin", "der", "(değişmez)"],
            ["Nötr", "des", "+(e)s"],
            ["Plural", "der", "(değişmez)"],
          ],
        },
      },
      {
        heading: "+(e)s Eki Kuralı",
        body: "Maskulin ve nötr: Kısa isimler → -s (des Autos, des Films). Uzun veya -s/-sch/-z/-x biten → -es (des Mannes, des Kindes). -s/-ss/-ß biten → -es zorunlu: des Hauses.",
        examples: [
          { de: "das Auto → des Autos", tr: "arabanın" },
          { de: "der Mann → des Mannes", tr: "adamın" },
          { de: "das Haus → des Hauses", tr: "evin" },
        ],
      },
      {
        heading: "von + Dativ Alternatifi",
        body: "Günlük konuşmada Genitiv yerine 'von + Dativ' sık kullanılır: das Auto von meinem Vater = das Auto meines Vaters.",
        examples: [
          { de: "das Auto meines Vaters = das Auto von meinem Vater", tr: "babamın arabası" },
          { de: "die Bücher meiner Schwester = die Bücher von meiner Schwester", tr: "kız kardeşimin kitapları" },
          { de: "der Name des Lehrers = der Name vom Lehrer", tr: "öğretmenin adı" },
        ],
      },
    ],
    exercises: {
      multipleChoice: [
        {
          id: 1,
          question: "Das ist das Auto ___ Mannes.",
          options: ["des", "der", "dem", "den"],
          correct: 0,
          explanation: "Mann = maskulin; Genitiv → des.",
        },
        {
          id: 2,
          question: "Die Tasche ___ Frau ist schön.",
          options: ["des", "dem", "den", "der"],
          correct: 3,
          explanation: "Frau = feminin; Genitiv → der.",
        },
        {
          id: 3,
          question: "Das Spielzeug ___ Kindes liegt hier.",
          options: ["der", "dem", "des", "die"],
          correct: 2,
          explanation: "Kind = nötr; Genitiv → des.",
        },
        {
          id: 4,
          question: "Die Namen ___ Schüler sind bekannt. (Plural)",
          options: ["des", "dem", "die", "der"],
          correct: 3,
          explanation: "Plural Genitiv → der.",
        },
        {
          id: 5,
          question: "Das ist das Haus ___ Lehrers.",
          options: ["der", "des", "dem", "den"],
          correct: 1,
          explanation: "Lehrer = maskulin; Genitiv → des; Lehrer+s = Lehrers.",
        },
        {
          id: 6,
          question: "Die Farbe ___ Autos ist rot.",
          options: ["des", "der", "dem", "die"],
          correct: 0,
          explanation: "Auto = nötr; Genitiv → des; Auto+s = Autos.",
        },
        {
          id: 7,
          question: "Das Ende ___ Films war gut.",
          options: ["der", "dem", "des", "die"],
          correct: 2,
          explanation: "Film = maskulin; Genitiv → des; Film+s = Films.",
        },
        {
          id: 8,
          question: "Das Büro ___ Chefin ist groß.",
          options: ["des", "der", "dem", "die"],
          correct: 1,
          explanation: "Chefin = feminin; Genitiv → der.",
        },
      ],
      fillInBlank: [
        {
          id: 1,
          before: "Das ist das Fahrrad",
          after: "Bruders.",
          answer: "des",
          hint: "Bruder = maskulin; Genitiv → des",
        },
        {
          id: 2,
          before: "Die Stimme",
          after: "Sängerin ist wunderschön.",
          answer: "der",
          hint: "Sängerin = feminin; Genitiv → der",
        },
        {
          id: 3,
          before: "Das Dach",
          after: "Hauses ist kaputt.",
          answer: "des",
          hint: "Haus = nötr; Genitiv → des",
        },
        {
          id: 4,
          before: "Die Meinungen",
          after: "Studenten sind verschieden.",
          answer: "der",
          hint: "Studenten = plural; Genitiv → der",
        },
        {
          id: 5,
          before: "Das ist das Auto",
          after: "Vaters.",
          answer: "meines",
          hint: "mein → Genitiv maskulin → meines",
        },
      ],
    },
  },
];
