export type HorenTeilType = "ansagen" | "gespraeche" | "informationen";

export interface HorenQuestion {
  id: number;
  shortAudio?: string;
  question: string;
  options?: string[];
  correct: number;
  explanation: string;
}

export interface HorenTeil {
  id: number;
  type: HorenTeilType;
  typeLabel: string;
  typeLabelTr: string;
  title: string;
  difficulty: 1 | 2 | 3;
  audioText?: string;
  maleSpeakers?: string[];
  questionFormat?: "mcq" | "richtigfalsch";
  instruction: string;
  questions: HorenQuestion[];
  xp: number;
}

export interface HorenProgress {
  [teilId: number]: { score: number; total: number };
}

// ── A2 — Teile 1–13: Ansagen ──────────────────────────────────────────────────

const A2_TEILE: HorenTeil[] = [
  {
    id: 1,
    type: "ansagen",
    typeLabel: "Ansagen & Durchsagen",
    typeLabelTr: "Duyurular ve Anonslar",
    title: "Alltägliche Ansagen",
    difficulty: 1,
    instruction: "Sie hören fünf kurze Ansagen. Hören Sie genau zu und wählen Sie die richtige Antwort.",
    questions: [
      {
        id: 1,
        shortAudio: "Sehr geehrte Kundinnen und Kunden, heute haben wir besondere Angebote in der Obstabteilung. Äpfel, zwei Kilo für nur einen Euro neunzig. Das Angebot gilt nur heute!",
        question: "Was ist heute im Supermarkt im Angebot?",
        options: ["Gemüse", "Obst", "Milchprodukte"],
        correct: 1,
        explanation: "'Obstabteilung' = meyve bölümü. Elma 2 kg 1,90 € özel fiyata sunuluyor.",
      },
      {
        id: 2,
        shortAudio: "Achtung auf Gleis drei! Der Intercity nach München hat heute leider etwa zwanzig Minuten Verspätung. Wir bitten um Ihr Verständnis.",
        question: "Was ist das Problem am Bahnhof?",
        options: ["Der Zug fährt von einem anderen Gleis ab.", "Der Zug kommt zwanzig Minuten später.", "Der Zug nach München fährt heute nicht."],
        correct: 1,
        explanation: "'Verspätung' = gecikme. Münih treni 20 dakika geç geliyor.",
      },
      {
        id: 3,
        shortAudio: "Sie haben die Praxis Dr. Müller angerufen. Unsere Sprechzeiten sind montags bis freitags von acht bis zwölf Uhr und dienstags und donnerstags auch von fünfzehn bis achtzehn Uhr.",
        question: "Wann hat die Arztpraxis auch nachmittags geöffnet?",
        options: ["Montags und mittwochs", "Dienstags und donnerstags", "Freitags und samstags"],
        correct: 1,
        explanation: "'dienstags und donnerstags auch von fünfzehn bis achtzehn Uhr' — Salı ve Perşembe öğleden sonra da açık.",
      },
      {
        id: 4,
        shortAudio: "Herzlich willkommen zum Stadtfest Heidelberg! Das Programm beginnt um sechzehn Uhr mit Livemusik. Um neunzehn Uhr gibt es eine große Tanzshow. Und um einundzwanzig Uhr startet das Feuerwerk.",
        question: "Wann beginnt die Tanzshow?",
        options: ["Um 16 Uhr", "Um 19 Uhr", "Um 21 Uhr"],
        correct: 1,
        explanation: "'um neunzehn Uhr gibt es eine große Tanzshow' — dans gösterisi saat 19:00'da.",
      },
      {
        id: 5,
        shortAudio: "Achtung, liebe Fahrgäste! Wegen einer Baustelle fährt die Linie Siebenundzwanzig heute nicht durch die Schillerstraße. Bitte steigen Sie an der Haltestelle Hauptbahnhof in die Umleitung ein.",
        question: "Warum gibt es eine Änderung bei der Buslinie?",
        options: ["Wegen eines Unfalls", "Wegen einer Baustelle", "Wegen schlechten Wetters"],
        correct: 1,
        explanation: "'wegen einer Baustelle' = bir inşaat nedeniyle güzergah değişti.",
      },
    ],
    xp: 40,
  },
  {
    id: 2,
    type: "ansagen",
    typeLabel: "Ansagen & Durchsagen",
    typeLabelTr: "Duyurular ve Anonslar",
    title: "Am Bahnhof",
    difficulty: 1,
    instruction: "Sie hören fünf kurze Durchsagen am Bahnhof. Wählen Sie die richtige Antwort.",
    questions: [
      {
        id: 1,
        shortAudio: "Achtung auf Gleis sieben! Der ICE zweihundert sieben nach Hamburg Hauptbahnhof fährt heute ausnahmsweise von Gleis sieben ab. Bitte beachten Sie die Gleisänderung.",
        question: "Von welchem Gleis fährt der ICE nach Hamburg?",
        options: ["Gleis 2", "Gleis 5", "Gleis 7"],
        correct: 2,
        explanation: "'fährt heute ausnahmsweise von Gleis sieben ab' — tren bugün 7. perondan kalkıyor.",
      },
      {
        id: 2,
        shortAudio: "Die S-Bahn Linie vier nach Flughafen Terminal Eins fährt in drei Minuten ab. Bitte einsteigen und Türen freihalten!",
        question: "Wohin fährt die S-Bahn Linie 4?",
        options: ["Zum Hauptbahnhof", "Zum Flughafen", "Zum Stadtpark"],
        correct: 1,
        explanation: "'nach Flughafen Terminal Eins' — havalimanı terminaline gidiyor.",
      },
      {
        id: 3,
        shortAudio: "Aus betrieblichen Gründen fällt der RegionalExpress nach Köln heute leider aus. Der nächste Zug fährt um sechzehn Uhr dreißig.",
        question: "Was passiert mit dem RegionalExpress nach Köln?",
        options: ["Er hat Verspätung.", "Er fährt heute nicht.", "Er fährt von einem anderen Gleis."],
        correct: 1,
        explanation: "'fällt aus' = iptal edildi. Sonraki tren 16:30'da.",
      },
      {
        id: 4,
        shortAudio: "Willkommen am Münchner Hauptbahnhof! Für Fragen steht Ihnen unser Service-Team am Informationsschalter in der Haupthalle zur Verfügung.",
        question: "Wo kann man am Hauptbahnhof Fragen stellen?",
        options: ["Am Fahrkartenautomat", "Am Informationsschalter", "Am Ausgang"],
        correct: 1,
        explanation: "'Service-Team am Informationsschalter' — bilgi gişesinde personel soruları yanıtlıyor.",
      },
      {
        id: 5,
        shortAudio: "Achtung auf Gleis neun! Bitte beachten Sie, dass das Einsteigen in den Intercity nach Frankfurt erst fünf Minuten vor Abfahrt möglich ist.",
        question: "Wann darf man in den Zug nach Frankfurt einsteigen?",
        options: ["Sofort", "5 Minuten vor Abfahrt", "10 Minuten vor Abfahrt"],
        correct: 1,
        explanation: "'erst fünf Minuten vor Abfahrt' — trene kalkıştan 5 dakika önce binebilirsiniz.",
      },
    ],
    xp: 40,
  },
  {
    id: 3,
    type: "ansagen",
    typeLabel: "Ansagen & Durchsagen",
    typeLabelTr: "Duyurular ve Anonslar",
    title: "Schule und Kindergarten",
    difficulty: 1,
    instruction: "Sie hören fünf Ansagen aus Schule und Kindergarten. Wählen Sie die richtige Antwort.",
    questions: [
      {
        id: 1,
        shortAudio: "Liebe Eltern, die Schule bleibt morgen wegen eines Lehrerstreiks geschlossen. Bitte organisieren Sie eine Betreuung für Ihre Kinder.",
        question: "Warum bleibt die Schule morgen geschlossen?",
        options: ["Wegen eines Feiertags", "Wegen eines Streiks", "Wegen Reparaturarbeiten"],
        correct: 1,
        explanation: "'Lehrerstreik' = öğretmen grevi nedeniyle okul yarın kapalı.",
      },
      {
        id: 2,
        shortAudio: "Aufmerksamkeit bitte! Die Elternversammlung für die Klassen drei und vier findet am Donnerstag um achtzehn Uhr in der Turnhalle statt.",
        question: "Wo findet die Elternversammlung statt?",
        options: ["Im Klassenraum", "In der Turnhalle", "In der Aula"],
        correct: 1,
        explanation: "'in der Turnhalle' — veli toplantısı spor salonunda.",
      },
      {
        id: 3,
        shortAudio: "Liebe Schülerinnen und Schüler, das Schulfest findet am letzten Freitag im Monat auf dem Schulhof statt. Bitte bringt Essen und Getränke zum Teilen mit.",
        question: "Was sollen die Schüler zum Schulfest mitbringen?",
        options: ["Spiele und Bücher", "Essen und Getränke", "Stühle und Tische"],
        correct: 1,
        explanation: "'bringt Essen und Getränke zum Teilen mit' — okul şenliği için yiyecek ve içecek getirin.",
      },
      {
        id: 4,
        shortAudio: "Der Schulbus für die Grundschule Birkenweg hat morgen fünfzehn Minuten Verspätung. Die Kinder werden um sieben Uhr fünfundvierzig abgeholt.",
        question: "Wann kommt der Schulbus morgen?",
        options: ["Um 7:30 Uhr", "Um 7:45 Uhr", "Um 8:00 Uhr"],
        correct: 1,
        explanation: "'um sieben Uhr fünfundvierzig' — otobüs yarın 7:45'te gelecek (15 dk geç).",
      },
      {
        id: 5,
        shortAudio: "Liebe Eltern des Kindergartens Sonnenschein! Aufgrund von Renovierungsarbeiten ist die Kita in der nächsten Woche nur von acht bis dreizehn Uhr geöffnet.",
        question: "Wie lange ist der Kindergarten nächste Woche geöffnet?",
        options: ["Normal bis 17 Uhr", "Nur bis 13 Uhr", "Gar nicht geöffnet"],
        correct: 1,
        explanation: "'nur von acht bis dreizehn Uhr' — tadilat nedeniyle kreş sadece 08:00-13:00 arası açık.",
      },
    ],
    xp: 40,
  },
  {
    id: 4,
    type: "ansagen",
    typeLabel: "Ansagen & Durchsagen",
    typeLabelTr: "Duyurular ve Anonslar",
    title: "Im Einkaufszentrum",
    difficulty: 2,
    instruction: "Sie hören fünf Ansagen aus einem Einkaufszentrum. Wählen Sie die richtige Antwort.",
    questions: [
      {
        id: 1,
        shortAudio: "Liebe Kundinnen und Kunden des Einkaufszentrums CityPark! Heute findet von vierzehn bis achtzehn Uhr ein großer Ausverkauf im zweiten Obergeschoss statt. Bis zu fünfzig Prozent Rabatt auf alle Sommermode!",
        question: "Wo findet der Ausverkauf statt?",
        options: ["Im Erdgeschoss", "Im zweiten Obergeschoss", "Im Untergeschoss"],
        correct: 1,
        explanation: "'im zweiten Obergeschoss' — indirim 2. katta, bugün 14:00-18:00 arası.",
      },
      {
        id: 2,
        shortAudio: "Achtung! Wir suchen die Eltern des kleinen Jonas. Ihr Kind wartet an der Kundeninfo im Erdgeschoss auf Sie. Bitte kommen Sie sofort dorthin.",
        question: "Wo wartet das Kind Jonas?",
        options: ["Am Ausgang", "An der Kundeninfo", "Beim Sicherheitsdienst"],
        correct: 1,
        explanation: "'an der Kundeninfo im Erdgeschoss' — çocuk zemin kattaki müşteri hizmetlerinde bekliyor.",
      },
      {
        id: 3,
        shortAudio: "Das Einkaufszentrum CityPark schließt heute ausnahmsweise bereits um zwanzig Uhr. Wir bitten alle Kunden, ihre Einkäufe bis dahin abzuschließen.",
        question: "Wann schließt das Einkaufszentrum heute?",
        options: ["Um 21 Uhr", "Um 20 Uhr", "Um 19 Uhr"],
        correct: 1,
        explanation: "'schließt heute ausnahmsweise bereits um zwanzig Uhr' — AVM bugün istisnai olarak 20:00'da kapanıyor.",
      },
      {
        id: 4,
        shortAudio: "Liebe Kunden, unser Parkhaus ist derzeit voll besetzt. Bitte nutzen Sie alternativ den öffentlichen Parkplatz gegenüber dem Einkaufszentrum.",
        question: "Warum sollen Kunden den anderen Parkplatz nutzen?",
        options: ["Das Parkhaus ist zu teuer.", "Das Parkhaus ist voll.", "Das Parkhaus ist geschlossen."],
        correct: 1,
        explanation: "'voll besetzt' = dolu. Otopark dolu olduğu için karşıdaki park alanı öneriliyor.",
      },
      {
        id: 5,
        shortAudio: "Heute Abend findet im Atrium des CityPark ein kostenloses Konzert statt. Ab achtzehn Uhr spielt die Band Sommernacht für Sie. Der Eintritt ist frei!",
        question: "Was ist der Eintritt für das Konzert?",
        options: ["5 Euro", "10 Euro", "Kostenlos"],
        correct: 2,
        explanation: "'Der Eintritt ist frei' = ücretsiz. Konser 18:00'de başlıyor.",
      },
    ],
    xp: 45,
  },
  {
    id: 5,
    type: "ansagen",
    typeLabel: "Ansagen & Durchsagen",
    typeLabelTr: "Duyurular ve Anonslar",
    title: "Im Krankenhaus",
    difficulty: 2,
    instruction: "Sie hören fünf Durchsagen aus einem Krankenhaus. Wählen Sie die richtige Antwort.",
    questions: [
      {
        id: 1,
        shortAudio: "Guten Morgen! Wir bitten alle Patienten, ihr Mobiltelefon im Wartezimmer auf lautlos zu stellen. Vielen Dank für Ihr Verständnis.",
        question: "Was sollen die Patienten tun?",
        options: ["Ihre Handys ausschalten", "Ihre Handys auf lautlos stellen", "Ihre Handys draußen lassen"],
        correct: 1,
        explanation: "'auf lautlos stellen' = sessiz moda almak. Bekleme odasında telefon sessize alınmalı.",
      },
      {
        id: 2,
        shortAudio: "Achtung! Die Notaufnahme ist wegen Überfüllung derzeit geschlossen. Bitte fahren Sie in die Klinik am Stadtpark, die in zehn Minuten erreichbar ist.",
        question: "Warum ist die Notaufnahme geschlossen?",
        options: ["Wegen Renovierung", "Wegen Überfüllung", "Wegen Personalmangels"],
        correct: 1,
        explanation: "'wegen Überfüllung' = doluluk nedeniyle acil servis kapalı. Alternatif klinik 10 dakika uzakta.",
      },
      {
        id: 3,
        shortAudio: "Liebe Besucher, die Besuchszeiten auf Station drei sind täglich von vierzehn bis achtzehn Uhr. Bitte beachten Sie, dass Kinder unter zwölf Jahren keinen Zutritt haben.",
        question: "Welche Besucher haben keinen Zutritt auf Station 3?",
        options: ["Ältere Menschen", "Kinder unter 12 Jahren", "Männer"],
        correct: 1,
        explanation: "'Kinder unter zwölf Jahren keinen Zutritt' — 12 yaşından küçük çocuklar koğuşa giremez.",
      },
      {
        id: 4,
        shortAudio: "Herr Dr. Weber wird gebeten, sofort auf die Station vier zu kommen. Herr Dr. Weber, bitte Station vier.",
        question: "Wer wird gerufen?",
        options: ["Eine Krankenschwester", "Herr Dr. Weber", "Ein Patient"],
        correct: 1,
        explanation: "Dr. Weber 4. koğuşa çağrılıyor — bu tür anonslar acil durumlarda yapılır.",
      },
      {
        id: 5,
        shortAudio: "Liebe Patienten der Röntgenabteilung! Aufgrund technischer Probleme kommt es heute zu Verzögerungen von circa einer Stunde. Wir bitten um Ihr Verständnis.",
        question: "Warum gibt es Verzögerungen in der Röntgenabteilung?",
        options: ["Wegen Personalmangels", "Wegen technischer Probleme", "Wegen zu vieler Patienten"],
        correct: 1,
        explanation: "'Aufgrund technischer Probleme' = teknik sorunlar nedeniyle yaklaşık 1 saatlik gecikme.",
      },
    ],
    xp: 45,
  },
  {
    id: 6,
    type: "ansagen",
    typeLabel: "Ansagen & Durchsagen",
    typeLabelTr: "Duyurular ve Anonslar",
    title: "Sport und Freizeit",
    difficulty: 1,
    instruction: "Sie hören fünf Ansagen aus Sport- und Freizeiteinrichtungen. Wählen Sie die richtige Antwort.",
    questions: [
      {
        id: 1,
        shortAudio: "Liebe Mitglieder des Sportvereins! Das Training am Dienstagabend fällt diese Woche aus. Der nächste Termin ist am kommenden Donnerstag um neunzehn Uhr.",
        question: "Wann ist das nächste Training?",
        options: ["Am Dienstag", "Am Donnerstag", "Am Freitag"],
        correct: 1,
        explanation: "'am kommenden Donnerstag um neunzehn Uhr' — bu haftaki salı antrenmanı iptal, sonraki Perşembe 19:00.",
      },
      {
        id: 2,
        shortAudio: "Das Freibad Sonnenbad öffnet diese Woche ausnahmsweise bereits um sieben Uhr. Die Öffnungszeiten sind von sieben bis zwanzig Uhr dreißig.",
        question: "Wann öffnet das Freibad diese Woche?",
        options: ["Um 8 Uhr", "Um 7 Uhr", "Um 9 Uhr"],
        correct: 1,
        explanation: "'öffnet diese Woche ausnahmsweise bereits um sieben Uhr' — bu hafta istisnai olarak 7:00'de açılıyor.",
      },
      {
        id: 3,
        shortAudio: "Achtung alle Tennisspieler! Die Plätze eins bis vier sind wegen Renovierungsarbeiten bis Freitag gesperrt. Bitte nutzen Sie die Plätze fünf bis acht.",
        question: "Welche Tennisplätze sind gesperrt?",
        options: ["Plätze 1–4", "Plätze 5–8", "Alle Plätze"],
        correct: 0,
        explanation: "'Plätze eins bis vier sind gesperrt' — tadilat nedeniyle 1-4. kortlar kapalı.",
      },
      {
        id: 4,
        shortAudio: "Die Fitnesskurse am Samstag beginnen diese Woche dreißig Minuten später. Yoga startet um zehn Uhr dreißig, Zumba um zwölf Uhr.",
        question: "Wann beginnt der Yogakurs am Samstag diese Woche?",
        options: ["Um 10:00 Uhr", "Um 10:30 Uhr", "Um 11:00 Uhr"],
        correct: 1,
        explanation: "'Yoga startet um zehn Uhr dreißig' — bu hafta yoga 10:30'da başlıyor (30 dk geç).",
      },
      {
        id: 5,
        shortAudio: "Der Schwimmkurs für Erwachsene am Montagabend ist leider ausgebucht. Für Anmeldungen zum nächsten Kurs im September können Sie sich ab sofort in der Rezeption eintragen.",
        question: "Was kann man ab sofort in der Rezeption tun?",
        options: ["Den aktuellen Kurs buchen", "Sich für den September-Kurs anmelden", "Eine Mitgliedschaft kaufen"],
        correct: 1,
        explanation: "'für den nächsten Kurs im September ab sofort eintragen' — Eylül kursu için şimdi kayıt yaptırabilirsiniz.",
      },
    ],
    xp: 40,
  },
  {
    id: 7,
    type: "ansagen",
    typeLabel: "Ansagen & Durchsagen",
    typeLabelTr: "Duyurular ve Anonslar",
    title: "Restaurant und Hotel",
    difficulty: 2,
    instruction: "Sie hören fünf Ansagen aus einem Restaurant oder Hotel. Wählen Sie die richtige Antwort.",
    questions: [
      {
        id: 1,
        shortAudio: "Willkommen im Hotel Bergblick! Unser Frühstücksbuffet wird täglich von sieben bis zehn Uhr dreißig im ersten Obergeschoss serviert.",
        question: "Wann wird das Frühstück serviert?",
        options: ["Von 6:00 bis 9:00 Uhr", "Von 7:00 bis 10:30 Uhr", "Von 8:00 bis 11:00 Uhr"],
        correct: 1,
        explanation: "'täglich von sieben bis zehn Uhr dreißig' — kahvaltı 7:00-10:30 arası.",
      },
      {
        id: 2,
        shortAudio: "Liebe Gäste des Restaurants Zum Löwen! Leider ist heute unsere Küche bis neunzehn Uhr geschlossen. Bitte kommen Sie zwischen zwölf und dreizehn Uhr oder ab neunzehn Uhr.",
        question: "Wann kann man heute im Restaurant essen?",
        options: ["Nur abends ab 19 Uhr", "Zwischen 12–13 Uhr oder ab 19 Uhr", "Ganztags"],
        correct: 1,
        explanation: "Mutfak 19:00'e kadar kapalı. 12-13 veya 19:00 sonrası gelebilirsiniz.",
      },
      {
        id: 3,
        shortAudio: "Das ist eine Nachricht für Herrn Schneider in Zimmer dreihundert zwei. Bitte melden Sie sich an der Rezeption. Sie haben ein Paket erhalten.",
        question: "Warum soll Herr Schneider zur Rezeption?",
        options: ["Sein Zimmer muss gewechselt werden.", "Er hat ein Paket bekommen.", "Jemand wartet auf ihn."],
        correct: 1,
        explanation: "'Sie haben ein Paket erhalten' — Bay Schneider'a bir paket gelmiş.",
      },
      {
        id: 4,
        shortAudio: "Liebe Hotelgäste, das Hallenbad und die Sauna sind morgen von acht bis vierzehn Uhr wegen Reinigungsarbeiten geschlossen. Ab vierzehn Uhr stehen sie wieder zur Verfügung.",
        question: "Warum ist das Hallenbad morgen geschlossen?",
        options: ["Wegen Reparaturen", "Wegen Reinigungsarbeiten", "Wegen eines Umbaus"],
        correct: 1,
        explanation: "'wegen Reinigungsarbeiten' = temizlik çalışmaları. Yarın 14:00'te tekrar açılıyor.",
      },
      {
        id: 5,
        shortAudio: "Guten Abend, liebe Restaurantgäste! Heute Abend empfehlen wir als Tagesgericht ein Wiener Schnitzel mit Kartoffelsalat für neun Euro neunzig. Guten Appetit!",
        question: "Was kostet das Tagesgericht heute Abend?",
        options: ["7,90 Euro", "9,90 Euro", "11,90 Euro"],
        correct: 1,
        explanation: "'für neun Euro neunzig' — günün yemeği (Wiener Schnitzel) 9,90 €.",
      },
    ],
    xp: 45,
  },
  {
    id: 8,
    type: "ansagen",
    typeLabel: "Ansagen & Durchsagen",
    typeLabelTr: "Duyurular ve Anonslar",
    title: "Bank und Post",
    difficulty: 2,
    instruction: "Sie hören fünf Ansagen von einer Bank oder Post. Wählen Sie die richtige Antwort.",
    questions: [
      {
        id: 1,
        shortAudio: "Guten Morgen! Sie haben die Deutsche Bank Filiale Marktstraße angerufen. Unsere Öffnungszeiten sind montags bis freitags von neun bis siebzehn Uhr und samstags von neun bis dreizehn Uhr.",
        question: "Wann hat die Bank am Samstag geöffnet?",
        options: ["9–17 Uhr", "9–13 Uhr", "10–14 Uhr"],
        correct: 1,
        explanation: "'samstags von neun bis dreizehn Uhr' — Cumartesi 9:00-13:00 arası açık.",
      },
      {
        id: 2,
        shortAudio: "Achtung, liebe Kundinnen und Kunden! Der Geldautomat in unserer Filiale ist derzeit außer Betrieb. Den nächsten Automaten finden Sie in der Poststraße dreißig.",
        question: "Was ist das Problem?",
        options: ["Die Filiale ist geschlossen.", "Der Geldautomat funktioniert nicht.", "Die Bank hat kein Geld mehr."],
        correct: 1,
        explanation: "'außer Betrieb' = arızalı/çalışmıyor. En yakın ATM Poststraße 30'da.",
      },
      {
        id: 3,
        shortAudio: "Sie haben die Postfiliale Schillerplatz angerufen. Pakete können Sie rund um die Uhr an unserer Packstation abgeben.",
        question: "Wann kann man an der Packstation Pakete abgeben?",
        options: ["Nur zu den Öffnungszeiten", "Nur nachts", "Rund um die Uhr"],
        correct: 2,
        explanation: "'rund um die Uhr an unserer Packstation' — 24 saat boyunca paket bırakabilirsiniz.",
      },
      {
        id: 4,
        shortAudio: "Bitte beachten Sie: Für die Auszahlung größerer Beträge in unserer Filiale benötigen Sie einen Termin. Termine können Sie online oder telefonisch vereinbaren.",
        question: "Wann braucht man einen Termin in der Filiale?",
        options: ["Für alle Bankgeschäfte", "Für große Auszahlungen", "Für Kontoabschlüsse"],
        correct: 1,
        explanation: "'Für die Auszahlung größerer Beträge' — büyük miktarda nakit çekimleri için randevu gerekiyor.",
      },
      {
        id: 5,
        shortAudio: "Ihre Bestellung wurde heute Morgen zugestellt. Da Sie nicht zu Hause waren, liegt das Paket beim Nachbarn in Wohnung fünf. Ihr DHL-Kurierservice.",
        question: "Wo ist das Paket jetzt?",
        options: ["Beim Absender", "Beim Nachbarn in Wohnung 5", "Im Postamt"],
        correct: 1,
        explanation: "'liegt das Paket beim Nachbarn in Wohnung fünf' — evde olmadığınız için paket 5. dairenin komşusuna bırakıldı.",
      },
    ],
    xp: 45,
  },
  {
    id: 9,
    type: "ansagen",
    typeLabel: "Ansagen & Durchsagen",
    typeLabelTr: "Duyurular ve Anonslar",
    title: "Wetter und Verkehr",
    difficulty: 2,
    instruction: "Sie hören fünf Ansagen über Wetter und Verkehr. Wählen Sie die richtige Antwort.",
    questions: [
      {
        id: 1,
        shortAudio: "Achtung Autofahrer! Auf der Autobahn acht zwischen München und Augsburg hat sich ein Stau von zehn Kilometern gebildet. Bitte rechnen Sie mit einer Wartezeit von etwa dreißig Minuten.",
        question: "Wie lang ist der Stau?",
        options: ["5 Kilometer", "10 Kilometer", "15 Kilometer"],
        correct: 1,
        explanation: "'ein Stau von zehn Kilometern' — A8'de 10 km trafik sıkışıklığı, yaklaşık 30 dakika bekleme.",
      },
      {
        id: 2,
        shortAudio: "Wetterbericht für Norddeutschland: Morgen wird es stark bewölkt mit Regen am Nachmittag. Die Temperaturen liegen zwischen acht und vierzehn Grad.",
        question: "Wie wird das Wetter morgen Nachmittag?",
        options: ["Sonnig und warm", "Bewölkt mit Regen", "Kalt mit Schnee"],
        correct: 1,
        explanation: "'stark bewölkt mit Regen am Nachmittag' — öğleden sonra bulutlu ve yağmurlu.",
      },
      {
        id: 3,
        shortAudio: "Die Sperrung der Hauptstraße wegen Bauarbeiten wird noch bis Ende des Monats andauern. Bitte nutzen Sie die ausgeschilderte Umleitung über die Ringstraße.",
        question: "Wie lange ist die Hauptstraße noch gesperrt?",
        options: ["Bis Ende der Woche", "Bis Ende des Monats", "Bis Ende des Jahres"],
        correct: 1,
        explanation: "'bis Ende des Monats' — ana cadde ay sonuna kadar kapalı.",
      },
      {
        id: 4,
        shortAudio: "Schneechaos im Süden Deutschlands! Autofahrern wird empfohlen, Winterreifen zu benutzen und langsam zu fahren.",
        question: "Was wird den Autofahrern empfohlen?",
        options: ["Zuhause zu bleiben", "Winterreifen zu benutzen", "Eine andere Route zu nehmen"],
        correct: 1,
        explanation: "'Winterreifen zu benutzen und langsam zu fahren' — kış lastiklerini kullanın ve yavaş sürün.",
      },
      {
        id: 5,
        shortAudio: "Der Flughafen Frankfurt gibt bekannt: Aufgrund des starken Nebels wurden heute Morgen zwölf Flüge gestrichen. Bitte informieren Sie sich bei Ihrer Fluggesellschaft.",
        question: "Warum wurden Flüge gestrichen?",
        options: ["Wegen eines Streiks", "Wegen starken Nebels", "Wegen eines Sturms"],
        correct: 1,
        explanation: "'aufgrund des starken Nebels' = yoğun sis nedeniyle 12 uçuş iptal edildi.",
      },
    ],
    xp: 45,
  },
  {
    id: 10,
    type: "ansagen",
    typeLabel: "Ansagen & Durchsagen",
    typeLabelTr: "Duyurular ve Anonslar",
    title: "Kultur und Events",
    difficulty: 2,
    instruction: "Sie hören fünf Ansagen über kulturelle Veranstaltungen. Wählen Sie die richtige Antwort.",
    questions: [
      {
        id: 1,
        shortAudio: "Herzlich willkommen im Stadtmuseum Hamburg! Heute Abend findet um neunzehn Uhr dreißig eine Sonderführung durch die neue Ausstellung statt. Tickets kosten zwölf Euro, ermäßigt acht Euro.",
        question: "Was kostet der Normalpreis für die Führung?",
        options: ["8 Euro", "12 Euro", "15 Euro"],
        correct: 1,
        explanation: "'Tickets kosten zwölf Euro, ermäßigt acht Euro' — normal bilet 12 €, indirimli 8 €.",
      },
      {
        id: 2,
        shortAudio: "Das Theater am Ring muss das Stück heute Abend leider absagen. Bereits gekaufte Karten werden an der Kasse zurückerstattet.",
        question: "Was passiert mit den bereits gekauften Karten?",
        options: ["Sie sind für den nächsten Termin gültig.", "Sie werden zurückerstattet.", "Sie werden nicht akzeptiert."],
        correct: 1,
        explanation: "'werden an der Kasse zurückerstattet' — kasadan iade alınabilir.",
      },
      {
        id: 3,
        shortAudio: "Das Open-Air-Konzert im Stadtpark beginnt heute um zwanzig Uhr. Bei Regen findet die Veranstaltung in der Stadthalle statt. Bitte informieren Sie sich bis siebzehn Uhr auf unserer Website.",
        question: "Was passiert bei Regen?",
        options: ["Das Konzert wird abgesagt.", "Das Konzert findet in der Stadthalle statt.", "Das Konzert wird verschoben."],
        correct: 1,
        explanation: "'Bei Regen findet die Veranstaltung in der Stadthalle statt' — yağmurda konser şehir salonuna taşınıyor.",
      },
      {
        id: 4,
        shortAudio: "Die Kunstausstellung Moderne Welten ist ab sofort im Kunstzentrum zu sehen. Öffnungszeiten: Dienstag bis Sonntag von zehn bis achtzehn Uhr. Montags geschlossen.",
        question: "Wann ist das Kunstzentrum montags geöffnet?",
        options: ["Von 10–18 Uhr", "Von 12–18 Uhr", "Montags geschlossen"],
        correct: 2,
        explanation: "'Montags geschlossen' — sanat merkezi Pazartesi günleri kapalıdır.",
      },
      {
        id: 5,
        shortAudio: "Liebe Kinogäste! Die Vorstellung um achtzehn Uhr dreißig ist bereits ausverkauft. Karten für die Spätvorstellung um einundzwanzig Uhr sind noch erhältlich.",
        question: "Welche Vorstellung ist noch nicht ausverkauft?",
        options: ["Die Vorstellung um 18:30 Uhr", "Die Vorstellung um 21:00 Uhr", "Beide sind ausverkauft"],
        correct: 1,
        explanation: "18:30 gösterimi tükendi. 21:00'deki gece gösterimi için hâlâ bilet var.",
      },
    ],
    xp: 45,
  },
  {
    id: 11,
    type: "ansagen",
    typeLabel: "Ansagen & Durchsagen",
    typeLabelTr: "Duyurular ve Anonslar",
    title: "Alltag in Deutschland",
    difficulty: 2,
    instruction: "Sie hören fünf Ansagen aus dem deutschen Alltag. Wählen Sie die richtige Antwort.",
    questions: [
      {
        id: 1,
        shortAudio: "Liebe Hausbewohner! Am Samstag findet von neun bis zwölf Uhr die jährliche Hausreinigung statt. Bitte räumen Sie Fahrräder und Kinderwagen aus dem Keller und dem Treppenhaus.",
        question: "Was sollen die Bewohner vor der Hausreinigung tun?",
        options: ["Die Wohnung aufräumen", "Fahrräder und Kinderwagen wegräumen", "Den Keller abschließen"],
        correct: 1,
        explanation: "'räumen Sie Fahrräder und Kinderwagen aus dem Keller' — bisiklet ve bebek arabalarını kaldırın.",
      },
      {
        id: 2,
        shortAudio: "Achtung! In unserer Straße gibt es morgen Wasserabsperrungen. Von sechs bis vierzehn Uhr steht kein Wasser zur Verfügung. Bitte horten Sie genug Trinkwasser.",
        question: "Was sollen die Anwohner tun?",
        options: ["Den Vermieter anrufen", "Genug Wasser vorrätig halten", "Die Wohnung verlassen"],
        correct: 1,
        explanation: "'Bitte horten Sie genug Trinkwasser' — yarın 6-14 arası su yok, önceden su depolayın.",
      },
      {
        id: 3,
        shortAudio: "Liebe Kunden! Unser neuer Lieferservice ist ab sofort aktiv. Mindestbestellwert ist fünfzehn Euro. Lieferzeiten täglich von elf bis zweiundzwanzig Uhr.",
        question: "Wie hoch ist der Mindestbestellwert?",
        options: ["10 Euro", "15 Euro", "20 Euro"],
        correct: 1,
        explanation: "'Mindestbestellwert ist fünfzehn Euro' — minimum sipariş tutarı 15 €.",
      },
      {
        id: 4,
        shortAudio: "Wichtige Information der Stadtverwaltung: Ab dem ersten Oktober gilt die neue Mülltrennung. Plastik und Metall kommen in die gelbe Tonne.",
        question: "Was kommt ab Oktober in die gelbe Tonne?",
        options: ["Papier und Pappe", "Plastik und Metall", "Glas und Verpackungen"],
        correct: 1,
        explanation: "'Plastik und Metall kommen in die gelbe Tonne' — 1 Ekim'den itibaren sarı çöp kutusuna.",
      },
      {
        id: 5,
        shortAudio: "Liebe Fahrgäste, der Aufzug am Bahnhof Westend ist bis auf Weiteres außer Betrieb. Rollstuhlfahrer und Fahrgäste mit Kinderwagen werden gebeten, den Bahnhof Ostend zu nutzen.",
        question: "Für wen ist diese Information besonders wichtig?",
        options: ["Für ältere Menschen", "Für Rollstuhlfahrer und Eltern mit Kinderwagen", "Für alle Fahrgäste"],
        correct: 1,
        explanation: "'Rollstuhlfahrer und Fahrgäste mit Kinderwagen' — asansör arızalı, bu kişiler en çok etkileniyor.",
      },
    ],
    xp: 45,
  },
  {
    id: 12,
    type: "ansagen",
    typeLabel: "Ansagen & Durchsagen",
    typeLabelTr: "Duyurular ve Anonslar",
    title: "Am Flughafen",
    difficulty: 2,
    instruction: "Sie hören fünf Durchsagen am Flughafen. Wählen Sie die richtige Antwort.",
    questions: [
      {
        id: 1,
        shortAudio: "Letzter Aufruf für Flug LH vierhundert elf nach London Heathrow! Bitte begeben Sie sich sofort zum Gate B dreiundzwanzig. Der Flug schließt in zehn Minuten.",
        question: "Was sollen die Passagiere sofort tun?",
        options: ["Zum Check-in gehen", "Zum Gate B23 gehen", "Die Bordkarte zeigen"],
        correct: 1,
        explanation: "'Bitte begeben Sie sich sofort zum Gate B dreiundzwanzig' — son çağrı, hemen B23 kapısına gidin.",
      },
      {
        id: 2,
        shortAudio: "Achtung! Ein schwarzer Koffer mit rotem Band wurde am Terminal zwei gefunden. Der Besitzer wird gebeten, sich beim Informationsschalter zu melden.",
        question: "Was wurde gefunden?",
        options: ["Eine Handtasche", "Ein schwarzer Koffer mit rotem Band", "Ein Reisepass"],
        correct: 1,
        explanation: "'Ein schwarzer Koffer mit rotem Band' — kırmızı bantlı siyah bavul bulunmuş.",
      },
      {
        id: 3,
        shortAudio: "Der Flug SK vierhundert nach Stockholm hat eine Verspätung von neunzig Minuten. Der neue Abflug ist um zwanzig Uhr fünfzehn.",
        question: "Wie viel Verspätung hat der Flug nach Stockholm?",
        options: ["30 Minuten", "60 Minuten", "90 Minuten"],
        correct: 2,
        explanation: "'eine Verspätung von neunzig Minuten' = 90 dakika gecikme.",
      },
      {
        id: 4,
        shortAudio: "Aus Sicherheitsgründen dürfen Flüssigkeiten über hundert Milliliter nicht im Handgepäck mitgeführt werden. Bitte packen Sie solche Artikel in Ihr aufgegebenes Gepäck.",
        question: "Was darf man nicht im Handgepäck haben?",
        options: ["Lebensmittel", "Flüssigkeiten über 100 ml", "Elektronische Geräte"],
        correct: 1,
        explanation: "'Flüssigkeiten über hundert Milliliter nicht im Handgepäck' — 100 ml üzeri sıvılar el bagajında yasak.",
      },
      {
        id: 5,
        shortAudio: "Willkommen am Flughafen München! Das Gepäckband für Flug LH fünfhundert aus New York befindet sich in Halle B, Band sieben.",
        question: "Wo ist das Gepäckband für den Flug aus New York?",
        options: ["Halle A, Band 3", "Halle B, Band 7", "Halle C, Band 2"],
        correct: 1,
        explanation: "'in Halle B, Band sieben' — New York uçuşunun bagajları B Salonu, 7. bant.",
      },
    ],
    xp: 50,
  },
  {
    id: 13,
    type: "ansagen",
    typeLabel: "Ansagen & Durchsagen",
    typeLabelTr: "Duyurular ve Anonslar",
    title: "Beim Amt und in der Stadt",
    difficulty: 2,
    instruction: "Sie hören fünf Ansagen von Ämtern und städtischen Einrichtungen. Wählen Sie die richtige Antwort.",
    questions: [
      {
        id: 1,
        shortAudio: "Sie haben das Bürgeramt der Stadt Köln angerufen. Wegen hoher Nachfrage bitten wir Sie, Termine ausschließlich online zu buchen. Spontane Besuche ohne Termin sind leider nicht möglich.",
        question: "Wie kann man jetzt einen Termin beim Bürgeramt bekommen?",
        options: ["Telefonisch anrufen", "Online buchen", "Persönlich vorbeikommen"],
        correct: 1,
        explanation: "'Termine ausschließlich online buchen' — randevular sadece çevrimiçi alınabilir.",
      },
      {
        id: 2,
        shortAudio: "Liebe Bürgerinnen und Bürger! Die Stadtbibliothek ist ab sofort auch samstags von zehn bis vierzehn Uhr geöffnet. Wir freuen uns auf Ihren Besuch.",
        question: "Was ist neu bei der Stadtbibliothek?",
        options: ["Sie hat jetzt längere Öffnungszeiten unter der Woche.", "Sie ist jetzt auch samstags geöffnet.", "Sie hat jetzt eine neue Adresse."],
        correct: 1,
        explanation: "'ab sofort auch samstags von zehn bis vierzehn Uhr' — kütüphane artık Cumartesi de açık.",
      },
      {
        id: 3,
        shortAudio: "Achtung! Wegen der Bauarbeiten am Rathausplatz ist das Parken in der Innenstadt bis Ende des Monats eingeschränkt. Bitte nutzen Sie die Parkhäuser am Stadtrand.",
        question: "Warum ist das Parken in der Innenstadt eingeschränkt?",
        options: ["Wegen einer Veranstaltung", "Wegen Bauarbeiten", "Wegen neuer Verkehrsregeln"],
        correct: 1,
        explanation: "'Wegen der Bauarbeiten am Rathausplatz' — belediye meydanındaki inşaat nedeniyle park kısıtlandı.",
      },
      {
        id: 4,
        shortAudio: "Sie haben die Ausländerbehörde angerufen. Unsere Warteschlange ist momentan sehr lang. Bitte besuchen Sie unsere Website für Online-Termine oder rufen Sie nach vierzehn Uhr zurück.",
        question: "Was empfiehlt die Ausländerbehörde?",
        options: ["Sofort persönlich zu kommen", "Online einen Termin zu buchen oder nach 14 Uhr anzurufen", "Eine E-Mail zu schreiben"],
        correct: 1,
        explanation: "'Website für Online-Termine oder nach vierzehn Uhr zurückrufen' — iki alternatif öneriyor.",
      },
      {
        id: 5,
        shortAudio: "Liebe Anwohner! Der Recyclinghof in der Berliner Straße ist ab nächster Woche montags und mittwochs von sieben bis siebzehn Uhr geöffnet. Freitags bleibt er geschlossen.",
        question: "Wann ist der Recyclinghof freitags geöffnet?",
        options: ["Von 7–17 Uhr", "Von 9–14 Uhr", "Freitags ist er geschlossen."],
        correct: 2,
        explanation: "'Freitags bleibt er geschlossen' — geri dönüşüm merkezi Cuma günleri kapalı.",
      },
    ],
    xp: 50,
  },

  // ── A2 — Teile 14–22: Gespräche ───────────────────────────────────────────

  {
    id: 14,
    type: "gespraeche",
    typeLabel: "Gespräch",
    typeLabelTr: "Konuşma",
    title: "Kinoabend planen",
    difficulty: 2,
    maleSpeakers: ["Stefan"],
    audioText:
      "Stefan: Hallo?\nAnna: Hallo Stefan, hier ist Anna. Störe ich gerade?\nStefan: Nein, nein, ich bin gerade zu Hause. Was gibt's?\nAnna: Ich wollte fragen, ob wir uns am Samstag treffen können. Ich möchte ins Kino gehen.\nStefan: Am Samstag? Leider kann ich da nicht, ich arbeite bis achtzehn Uhr.\nAnna: Oh schade! Und am Sonntag?\nStefan: Sonntag passt mir gut. Was läuft denn im Kino?\nAnna: Der neue Film mit Julia Roberts. Er läuft um halb neun abends.\nStefan: Um zwanzig Uhr dreißig? Das ist etwas spät für mich. Können wir eine frühere Vorstellung nehmen?\nAnna: Ja, es gibt auch eine um sechzehn Uhr.\nStefan: Das ist perfekt! Sollen wir uns davor noch etwas essen gehen?\nAnna: Gerne! Wie wäre es mit dem neuen italienischen Restaurant am Marktplatz?\nStefan: Super! Dann treffen wir uns um vierzehn Uhr am Marktplatz.\nAnna: Einverstanden. Bis Sonntag!\nStefan: Bis Sonntag, tschüss!",
    instruction: "Sie hören ein Telefongespräch zwischen Anna und Stefan. Wählen Sie die richtige Antwort.",
    questions: [
      {
        id: 1,
        question: "Warum kann Stefan am Samstag nicht ins Kino gehen?",
        options: ["Er ist krank.", "Er arbeitet bis 18 Uhr.", "Er hat keine Lust."],
        correct: 1,
        explanation: "'ich arbeite bis achtzehn Uhr' — Stefan Cumartesi akşam 18:00'e kadar çalışıyor.",
      },
      {
        id: 2,
        question: "Für welche Filmvorstellung entscheiden sie sich?",
        options: ["Um 20:30 Uhr", "Um 16:00 Uhr", "Um 14:00 Uhr"],
        correct: 1,
        explanation: "20:30 çok geç olduğu için 16:00'lık gösterimi seçiyorlar.",
      },
      {
        id: 3,
        question: "Wo wollen sie essen gehen?",
        options: ["In einem chinesischen Restaurant", "In einem türkischen Restaurant", "In einem italienischen Restaurant"],
        correct: 2,
        explanation: "'neuen italienischen Restaurant am Marktplatz' — Marktplatz'taki yeni İtalyan restoranı.",
      },
      {
        id: 4,
        question: "Um wie viel Uhr treffen sie sich?",
        options: ["Um 12 Uhr", "Um 14 Uhr", "Um 16 Uhr"],
        correct: 1,
        explanation: "'treffen wir uns um vierzehn Uhr am Marktplatz' — saat 14:00'te buluşuyorlar.",
      },
      {
        id: 5,
        question: "Was machen sie zuerst?",
        options: ["Kino", "Essen gehen", "Spazieren gehen"],
        correct: 1,
        explanation: "Önce saat 14:00'te buluşup yemek yiyorlar, sonra 16:00'lık filme gidiyorlar.",
      },
    ],
    xp: 50,
  },
  {
    id: 15,
    type: "gespraeche",
    typeLabel: "Gespräch",
    typeLabelTr: "Konuşma",
    title: "Wohnungssuche",
    difficulty: 2,
    maleSpeakers: ["Markus"],
    audioText:
      "Frau Koch: Koch, guten Tag!\nMarkus: Guten Tag, mein Name ist Markus Berger. Ich rufe wegen der Wohnungsanzeige an.\nFrau Koch: Ah ja! Die Zweizimmerwohnung in der Gartenstraße?\nMarkus: Genau. Ist die Wohnung noch frei?\nFrau Koch: Ja, sie ist noch zu haben. Die Wohnung ist siebenundvierzig Quadratmeter groß.\nMarkus: Und wie hoch ist die Miete?\nFrau Koch: Siebenhundertfünfzig Euro warm, inklusive Heizung und Wasser.\nMarkus: Das klingt gut. Wann könnte ich sie besichtigen?\nFrau Koch: Wie wäre es übermorgen, Mittwoch, um siebzehn Uhr?\nMarkus: Mittwoch um siebzehn Uhr passt mir gut. Gibt es auch einen Parkplatz?\nFrau Koch: Nein, leider nicht. Aber es gibt in der Nähe eine Tiefgarage für fünfzig Euro im Monat.\nMarkus: Gut zu wissen. Wie lange steht die Wohnung schon leer?\nFrau Koch: Erst seit zwei Wochen. Der letzte Mieter hat gut auf sie aufgepasst.\nMarkus: Super. Dann freue ich mich auf den Termin am Mittwoch!\nFrau Koch: Bis Mittwoch dann. Auf Wiederhören!",
    instruction: "Sie hören ein Telefongespräch über eine Wohnungssuche. Wählen Sie die richtige Antwort.",
    questions: [
      {
        id: 1,
        question: "Wie groß ist die Wohnung?",
        options: ["37 Quadratmeter", "47 Quadratmeter", "57 Quadratmeter"],
        correct: 1,
        explanation: "'siebenundvierzig Quadratmeter groß' — daire 47 m².",
      },
      {
        id: 2,
        question: "Wie hoch ist die Warmmiete?",
        options: ["650 Euro", "750 Euro", "850 Euro"],
        correct: 1,
        explanation: "'Siebenhundertfünfzig Euro warm' — ısıtma ve su dahil 750 €.",
      },
      {
        id: 3,
        question: "Wann ist der Besichtigungstermin?",
        options: ["Montag um 17 Uhr", "Mittwoch um 17 Uhr", "Freitag um 17 Uhr"],
        correct: 1,
        explanation: "'Mittwoch um siebzehn Uhr' — Çarşamba 17:00'de görüntüleme.",
      },
      {
        id: 4,
        question: "Gibt es einen Parkplatz bei der Wohnung?",
        options: ["Ja, kostenlos.", "Nein, aber eine Tiefgarage für 50 €.", "Nein, gar nicht."],
        correct: 1,
        explanation: "'Nein, leider nicht. Aber Tiefgarage für fünfzig Euro im Monat' — dairede park yok ama yakında 50 €/ay garaj var.",
      },
      {
        id: 5,
        question: "Wie lange steht die Wohnung schon leer?",
        options: ["Seit zwei Monaten", "Seit zwei Wochen", "Seit drei Tagen"],
        correct: 1,
        explanation: "'Erst seit zwei Wochen' — daire sadece 2 haftadır boş.",
      },
    ],
    xp: 50,
  },
  {
    id: 16,
    type: "gespraeche",
    typeLabel: "Gespräch",
    typeLabelTr: "Konuşma",
    title: "Beim Arzt",
    difficulty: 2,
    maleSpeakers: ["Dr. Braun"],
    audioText:
      "Dr. Braun: Guten Morgen, Frau Hoffmann. Was kann ich für Sie tun?\nLisa: Guten Morgen, Herr Doktor. Ich habe seit drei Tagen starke Halsschmerzen und ein bisschen Fieber.\nDr. Braun: Haben Sie auch Husten oder Schnupfen?\nLisa: Ja, ich huste ein bisschen, aber keinen Schnupfen.\nDr. Braun: Ich schaue mal in Ihren Hals. Öffnen Sie bitte den Mund... Der Hals ist sehr rot. Das sieht nach einer Halsentzündung aus.\nLisa: Muss ich Antibiotika nehmen?\nDr. Braun: Ich möchte zuerst einen Abstrich machen. Wie hoch ist Ihr Fieber?\nLisa: Heute Morgen war es achtunddreißig Komma fünf.\nDr. Braun: Das ist erhöht, aber noch nicht zu hoch. Nehmen Sie Ibuprofen gegen die Schmerzen und das Fieber. Und bitte viel trinken und ausruhen.\nLisa: Soll ich auch zuhause bleiben?\nDr. Braun: Ja, ich schreibe Ihnen für zwei Tage eine Krankmeldung. Kommen Sie in drei Tagen wieder, wenn es nicht besser wird.\nLisa: Danke, Herr Doktor. Auf Wiedersehen.",
    instruction: "Sie hören ein Gespräch zwischen einer Patientin und einem Arzt. Wählen Sie die richtige Antwort.",
    questions: [
      {
        id: 1,
        question: "Was sind Lisas Symptome?",
        options: ["Nur Fieber", "Halsschmerzen, Fieber und Husten", "Schnupfen und Kopfschmerzen"],
        correct: 1,
        explanation: "Lisa hat Halsschmerzen, Fieber und leichten Husten, aber keinen Schnupfen.",
      },
      {
        id: 2,
        question: "Was vermutet der Arzt?",
        options: ["Eine Erkältung", "Eine Halsentzündung", "Eine Grippe"],
        correct: 1,
        explanation: "'Das sieht nach einer Halsentzündung aus' — doktor boğaz iltihabı şüpheliyor.",
      },
      {
        id: 3,
        question: "Wie hoch ist Lisas Fieber?",
        options: ["37,5 Grad", "38,0 Grad", "38,5 Grad"],
        correct: 2,
        explanation: "'achtunddreißig Komma fünf' = 38,5 derece.",
      },
      {
        id: 4,
        question: "Was soll Lisa gegen Fieber nehmen?",
        options: ["Antibiotika", "Ibuprofen", "Vitamin C"],
        correct: 1,
        explanation: "'Nehmen Sie Ibuprofen gegen die Schmerzen und das Fieber' — ağrı ve ateş için İbuprofen.",
      },
      {
        id: 5,
        question: "Für wie viele Tage bekommt Lisa eine Krankmeldung?",
        options: ["Für einen Tag", "Für zwei Tage", "Für drei Tage"],
        correct: 1,
        explanation: "'ich schreibe Ihnen für zwei Tage eine Krankmeldung' — 2 günlük istirahat raporu.",
      },
    ],
    xp: 50,
  },
  {
    id: 17,
    type: "gespraeche",
    typeLabel: "Gespräch",
    typeLabelTr: "Konuşma",
    title: "Im Restaurant",
    difficulty: 1,
    maleSpeakers: ["Kellner"],
    audioText:
      "Kellner: Guten Abend! Haben Sie reserviert?\nTom: Ja, auf den Namen Weber, für zwei Personen.\nKellner: Ah, Weber für zwei. Kommen Sie bitte mit, Ihr Tisch ist dort drüben. Hier ist die Speisekarte.\nTom: Danke. Was können Sie empfehlen?\nKellner: Heute ist unser Tagesgericht Lachsfilet mit Kartoffeln und Salat. Als Vorspeise haben wir eine hausgemachte Suppe.\nTom: Ich nehme die Suppe als Vorspeise und dann den Lachs.\nKellner: Sehr gerne. Und etwas zu trinken?\nTom: Ein Glas Weißwein bitte, und ein Wasser.\nKellner: Naturell oder mit Kohlensäure?\nTom: Naturell bitte.\nKellner: Noch etwas?\nTom: Ja, meine Begleiterin möchte vegetarisch essen. Gibt es etwas ohne Fleisch?\nKellner: Natürlich! Wir haben heute Gemüsepasta mit Tomatensauce, sehr empfehlenswert.\nTom: Perfekt, dann bestellen wir das für sie.\nKellner: Ich bringe erst mal Ihre Getränke. Guten Appetit schon mal!",
    instruction: "Sie hören ein Gespräch in einem Restaurant. Wählen Sie die richtige Antwort.",
    questions: [
      {
        id: 1,
        question: "Auf welchen Namen hat Tom reserviert?",
        options: ["Auf den Namen Müller", "Auf den Namen Weber", "Auf den Namen Fischer"],
        correct: 1,
        explanation: "'auf den Namen Weber, für zwei Personen' — Weber adına 2 kişilik rezervasyon.",
      },
      {
        id: 2,
        question: "Was ist das Tagesgericht?",
        options: ["Schnitzel mit Pommes", "Lachsfilet mit Kartoffeln und Salat", "Pasta mit Tomatensauce"],
        correct: 1,
        explanation: "'Lachsfilet mit Kartoffeln und Salat' — günün yemeği.",
      },
      {
        id: 3,
        question: "Was bestellt Tom als Vorspeise?",
        options: ["Einen Salat", "Eine Suppe", "Brot und Butter"],
        correct: 1,
        explanation: "'Ich nehme die Suppe als Vorspeise' — başlangıç olarak çorba.",
      },
      {
        id: 4,
        question: "Welches Wasser möchte Tom?",
        options: ["Mit Kohlensäure", "Naturell", "Warmes Wasser"],
        correct: 1,
        explanation: "'Naturell bitte' = köpüksüz/düz su.",
      },
      {
        id: 5,
        question: "Was isst Toms Begleiterin?",
        options: ["Lachsfilet", "Schnitzel", "Gemüsepasta"],
        correct: 2,
        explanation: "'Gemüsepasta mit Tomatensauce' — arkadaşı vejeteryan, domates soslu makarna seçiyor.",
      },
    ],
    xp: 45,
  },
  {
    id: 18,
    type: "gespraeche",
    typeLabel: "Gespräch",
    typeLabelTr: "Konuşma",
    title: "Jobinterview vorbereiten",
    difficulty: 2,
    maleSpeakers: ["Michael"],
    audioText:
      "Sarah: Michael, ich habe morgen ein Vorstellungsgespräch und bin total nervös.\nMichael: Hey, das ist doch super! Bei welcher Firma?\nSarah: Bei einer Marketing-Agentur in der Innenstadt. Die Stelle ist als Grafikdesignerin.\nMichael: Perfekt, das passt zu deiner Ausbildung! Was ziehst du an?\nSarah: Ich dachte an meinen blauen Blazer mit schwarzer Hose. Ist das zu formell?\nMichael: Nein, das klingt gut. Business-Casual ist immer richtig für ein Vorstellungsgespräch.\nSarah: Und was soll ich über mich erzählen?\nMichael: Fang mit deiner Ausbildung an, dann deine Erfahrungen, und was dich an der Stelle interessiert. Aber halte es kurz — maximal drei Minuten.\nSarah: Was ist, wenn sie mich nach meinen Schwächen fragen?\nMichael: Nenn eine echte Schwäche, aber eine, an der du arbeitest. Zum Beispiel: Ich bin manchmal zu perfektionistisch.\nSarah: Guter Tipp! Und wann soll ich dort sein?\nMichael: Lieber zehn Minuten früher als pünktlich. Und vergiss deine Bewerbungsmappe nicht!\nSarah: Danke, Michael, du hast mir sehr geholfen!\nMichael: Viel Erfolg morgen!",
    instruction: "Sie hören ein Gespräch über die Vorbereitung auf ein Vorstellungsgespräch. Wählen Sie die richtige Antwort.",
    questions: [
      {
        id: 1,
        question: "Für welchen Beruf bewirbt sich Sarah?",
        options: ["Als Marketingmanagerin", "Als Grafikdesignerin", "Als Buchhalterin"],
        correct: 1,
        explanation: "'Die Stelle ist als Grafikdesignerin' — grafik tasarımcısı pozisyonu için başvuruyor.",
      },
      {
        id: 2,
        question: "Was plant Sarah zu tragen?",
        options: ["Ein schwarzes Kleid", "Blauen Blazer mit schwarzer Hose", "Jeans und T-Shirt"],
        correct: 1,
        explanation: "'meinen blauen Blazer mit schwarzer Hose' — mavi blazer ve siyah pantolon.",
      },
      {
        id: 3,
        question: "Wie lange sollte die Selbstvorstellung maximal dauern?",
        options: ["Eine Minute", "Drei Minuten", "Fünf Minuten"],
        correct: 1,
        explanation: "'maximal drei Minuten' — kendini tanıtma en fazla 3 dakika sürmeli.",
      },
      {
        id: 4,
        question: "Was rät Michael bei der Frage nach Schwächen?",
        options: ["Keine Schwächen nennen", "Eine echte, verbesserliche Schwäche nennen", "Eine erfundene Schwäche nennen"],
        correct: 1,
        explanation: "'eine echte Schwäche, aber eine, an der du arbeitest' — gerçek ama üzerinde çalıştığın bir zayıflık söyle.",
      },
      {
        id: 5,
        question: "Wann soll Sarah zum Vorstellungsgespräch erscheinen?",
        options: ["Pünktlich", "10 Minuten früher", "30 Minuten früher"],
        correct: 1,
        explanation: "'Lieber zehn Minuten früher als pünktlich' — tam saatinde değil, 10 dakika erken git.",
      },
    ],
    xp: 50,
  },
  {
    id: 19,
    type: "gespraeche",
    typeLabel: "Gespräch",
    typeLabelTr: "Konuşma",
    title: "Urlaub planen",
    difficulty: 2,
    maleSpeakers: ["Jonas"],
    audioText:
      "Lena: Jonas, wir müssen endlich unseren Sommerurlaub planen. Wohin soll es gehen?\nJonas: Ich dachte an Kroatien. Das Meer, die Sonne...\nLena: Kroatien ist schön, aber letztes Jahr waren wir schon am Meer. Wie wäre es mit einer Städtereise? Prag?\nJonas: Prag finde ich gut. Günstig und viele Sehenswürdigkeiten. Wann fahren wir?\nLena: Ende Juli, wenn die Kinder schulfrei haben. Etwa zehn Tage.\nJonas: Zehn Tage ist perfekt. Fliegen wir oder fahren wir mit dem Zug?\nLena: Der Zug ist günstiger und wir sehen mehr. Das Ticket von München nach Prag kostet nur neunzig Euro pro Person.\nJonas: Gut, dann nehmen wir den Zug. Und wo wohnen wir?\nLena: Ich habe ein nettes Hotel in der Altstadt gefunden. Frühstück inklusive, neunzig Euro pro Nacht.\nJonas: Das klingt vernünftig. Hast du schon gebucht?\nLena: Nein, ich warte noch auf deine Zustimmung. Soll ich jetzt buchen?\nJonas: Ja, buch es! Ich freue mich schon!\nLena: Wunderbar. Dann buche ich heute noch.",
    instruction: "Sie hören ein Gespräch über Urlaubsplanung. Wählen Sie die richtige Antwort.",
    questions: [
      {
        id: 1,
        question: "Wohin fahren Lena und Jonas im Urlaub?",
        options: ["Nach Kroatien", "Nach Prag", "Nach Wien"],
        correct: 1,
        explanation: "Jonas schlug Kroatien vor, aber sie entscheiden sich gemeinsam für Prag.",
      },
      {
        id: 2,
        question: "Wann fahren sie in Urlaub?",
        options: ["Anfang Juli", "Ende Juli", "Ende August"],
        correct: 1,
        explanation: "'Ende Juli, wenn die Kinder schulfrei haben' — çocuklar tatile girince Temmuz sonu.",
      },
      {
        id: 3,
        question: "Wie reisen sie nach Prag?",
        options: ["Mit dem Flugzeug", "Mit dem Auto", "Mit dem Zug"],
        correct: 2,
        explanation: "'Der Zug ist günstiger und wir sehen mehr' — tren daha ucuz ve manzaralı.",
      },
      {
        id: 4,
        question: "Was kostet das Zugticket pro Person?",
        options: ["70 Euro", "90 Euro", "110 Euro"],
        correct: 1,
        explanation: "'kostet nur neunzig Euro pro Person' — kişi başı 90 €.",
      },
      {
        id: 5,
        question: "Was ist im Hotel inklusive?",
        options: ["Das Abendessen", "Das Frühstück", "Der Parkplatz"],
        correct: 1,
        explanation: "'Frühstück inklusive, neunzig Euro pro Nacht' — 90 €/gece, kahvaltı dahil.",
      },
    ],
    xp: 50,
  },
  {
    id: 20,
    type: "gespraeche",
    typeLabel: "Gespräch",
    typeLabelTr: "Konuşma",
    title: "Beim Einkaufen",
    difficulty: 1,
    maleSpeakers: [],
    audioText:
      "Verkäuferin: Guten Tag! Kann ich Ihnen helfen?\nEmma: Ja, gerne. Ich suche ein Kleid für eine Hochzeit.\nVerkäuferin: Sehr gerne! Für welchen Anlass genau — Sommer- oder Abendveranstaltung?\nEmma: Es ist eine Sommerparty im Garten.\nVerkäuferin: Dann empfehle ich etwas Leichtes und Buntes. Was ist Ihre Größe?\nEmma: Ich trage Größe sechsunddreißig.\nVerkäuferin: Dann hätten wir dieses grüne Kleid oder das blaue dort. Das grüne ist aus Leinen, perfekt für den Sommer.\nEmma: Oh, das grüne gefällt mir! Kann ich es anprobieren?\nVerkäuferin: Natürlich! Die Umkleidekabinen sind dort rechts.\nEmma: Es passt gut, aber es ist etwas kurz. Haben Sie es auch etwas länger?\nVerkäuferin: Ja, wir haben das gleiche Modell in lang. Einen Moment... Hier, bitte.\nEmma: Das ist perfekt! Was kostet es?\nVerkäuferin: Neunundsiebzig Euro neunzig. Wir haben gerade zehn Prozent Rabatt auf alle Sommerkleider.\nEmma: Super! Dann nehme ich es.",
    instruction: "Sie hören ein Gespräch in einem Bekleidungsgeschäft. Wählen Sie die richtige Antwort.",
    questions: [
      {
        id: 1,
        question: "Wofür sucht Emma ein Kleid?",
        options: ["Für eine Geburtstagsparty", "Für eine Hochzeit", "Für ein Vorstellungsgespräch"],
        correct: 1,
        explanation: "'Ich suche ein Kleid für eine Hochzeit' — düğün için elbise arıyor.",
      },
      {
        id: 2,
        question: "Welche Größe trägt Emma?",
        options: ["Größe 34", "Größe 36", "Größe 38"],
        correct: 1,
        explanation: "'Ich trage Größe sechsunddreißig' — Emma 36 beden giyiyor.",
      },
      {
        id: 3,
        question: "Aus welchem Material ist das grüne Kleid?",
        options: ["Aus Baumwolle", "Aus Seide", "Aus Leinen"],
        correct: 2,
        explanation: "'Das grüne ist aus Leinen, perfekt für den Sommer' — yeşil elbise keten kumaş.",
      },
      {
        id: 4,
        question: "Was war das Problem mit dem ersten Kleid?",
        options: ["Es war zu teuer.", "Es war zu kurz.", "Es war zu groß."],
        correct: 1,
        explanation: "'es ist etwas kurz' — ilk elbise biraz kısaydı.",
      },
      {
        id: 5,
        question: "Wie viel Rabatt gibt es gerade?",
        options: ["5 Prozent", "10 Prozent", "20 Prozent"],
        correct: 1,
        explanation: "'zehn Prozent Rabatt auf alle Sommerkleider' — tüm yaz elbiselerde %10 indirim.",
      },
    ],
    xp: 45,
  },
  {
    id: 21,
    type: "gespraeche",
    typeLabel: "Gespräch",
    typeLabelTr: "Konuşma",
    title: "Sportverein beitreten",
    difficulty: 2,
    maleSpeakers: ["David"],
    audioText:
      "Frau Müller: Sportverein Blau-Weiß, guten Tag!\nDavid: Guten Tag, mein Name ist David. Ich möchte gerne Mitglied in Ihrem Fußballverein werden.\nFrau Müller: Herzlich willkommen! Wie alt sind Sie?\nDavid: Ich bin einundzwanzig Jahre alt.\nFrau Müller: Super, dann gehören Sie zur Erwachsenenmannschaft. Haben Sie schon Fußball gespielt?\nDavid: Ja, ich habe früher in einem Jugendverein gespielt, aber seit drei Jahren nicht mehr.\nFrau Müller: Kein Problem! Wir haben Trainingseinheiten dienstags und donnerstags, jeweils von siebzehn bis neunzehn Uhr.\nDavid: Und was kostet die Mitgliedschaft?\nFrau Müller: Dreißig Euro im Monat, inklusive Trainingskleidung und Umkleidekabinen.\nDavid: Sehr günstig! Wann kann ich mit dem Training beginnen?\nFrau Müller: Am nächsten Dienstag können Sie einfach vorbeikommen und mitmachen. Bringen Sie bitte Sportschuhe mit.\nDavid: Soll ich mich vorher anmelden?\nFrau Müller: Nein, kommen Sie einfach vorbei. Ich bin dann da und zeige Ihnen alles.\nDavid: Wunderbar, vielen Dank! Bis Dienstag!",
    instruction: "Sie hören ein Gespräch über den Beitritt in einen Sportverein. Wählen Sie die richtige Antwort.",
    questions: [
      {
        id: 1,
        question: "Wie alt ist David?",
        options: ["18 Jahre", "21 Jahre", "25 Jahre"],
        correct: 1,
        explanation: "'Ich bin einundzwanzig Jahre alt' — David 21 yaşında.",
      },
      {
        id: 2,
        question: "Wann finden die Trainingseinheiten statt?",
        options: ["Montags und mittwochs, 17–19 Uhr", "Dienstags und donnerstags, 17–19 Uhr", "Freitags und samstags, 18–20 Uhr"],
        correct: 1,
        explanation: "'dienstags und donnerstags, jeweils von siebzehn bis neunzehn Uhr' — Salı ve Perşembe 17-19.",
      },
      {
        id: 3,
        question: "Was kostet die Mitgliedschaft pro Monat?",
        options: ["20 Euro", "30 Euro", "50 Euro"],
        correct: 1,
        explanation: "'Dreißig Euro im Monat' — aylık üyelik ücreti 30 €.",
      },
      {
        id: 4,
        question: "Wann kann David mit dem Training beginnen?",
        options: ["Sofort", "Am nächsten Dienstag", "Erst nächsten Monat"],
        correct: 1,
        explanation: "'Am nächsten Dienstag können Sie einfach vorbeikommen' — gelecek Salı başlayabilir.",
      },
      {
        id: 5,
        question: "Muss David sich vorher anmelden?",
        options: ["Ja, online.", "Ja, telefonisch.", "Nein, einfach vorbeikommen."],
        correct: 2,
        explanation: "'Nein, kommen Sie einfach vorbei' — önceden kayıt gerekmiyor, doğrudan gidebilir.",
      },
    ],
    xp: 50,
  },
  {
    id: 22,
    type: "gespraeche",
    typeLabel: "Gespräch",
    typeLabelTr: "Konuşma",
    title: "Geburtstagsfeier planen",
    difficulty: 2,
    maleSpeakers: [],
    audioText:
      "Clara: Sophie, Mamas Geburtstag ist in zwei Wochen. Wir müssen was organisieren!\nSophie: Ich weiß! Ich dachte an eine Überraschungsparty.\nClara: Super Idee! Aber wo? Bei dir oder bei mir?\nSophie: Bei mir, meine Wohnung ist größer. Ich kann bis zu dreißig Personen einladen.\nClara: Gut. Wie viele Leute sollen kommen?\nSophie: Familie und enge Freunde, also etwa zwanzig Personen.\nClara: Was machst du mit dem Essen? Selbst kochen oder catern lassen?\nSophie: Ich dachte an Fingerfood. Ich mache ein paar Sachen selbst und bestelle den Rest beim Partyservice.\nClara: Und die Deko? Mama mag Blumen.\nSophie: Ich kaufe weiße und gelbe Blumen. Und du kannst die Torte besorgen, oder?\nClara: Ja, natürlich. Von welcher Bäckerei?\nSophie: Vom Café Süß in der Stadtmitte. Die machen die besten Torten.\nClara: Einverstanden. Ich bestelle eine mit Erdbeeren, die mag Mama am liebsten.\nSophie: Perfekt! Und vergiss nicht — es ist eine Überraschung!",
    instruction: "Sie hören ein Gespräch über eine Geburtstagsparty. Wählen Sie die richtige Antwort.",
    questions: [
      {
        id: 1,
        question: "Bei wem findet die Party statt?",
        options: ["Bei Clara", "Bei Sophie", "Bei der Mutter"],
        correct: 1,
        explanation: "'Bei mir, meine Wohnung ist größer' — parti Sophie'nin evinde.",
      },
      {
        id: 2,
        question: "Wie viele Personen werden eingeladen?",
        options: ["Etwa 10 Personen", "Etwa 20 Personen", "Etwa 30 Personen"],
        correct: 1,
        explanation: "'etwa zwanzig Personen' — yaklaşık 20 kişi davet edilecek.",
      },
      {
        id: 3,
        question: "Was gibt es zu essen?",
        options: ["Ein großes Buffet", "Fingerfood", "Ein 3-Gänge-Menü"],
        correct: 1,
        explanation: "'Ich dachte an Fingerfood' — yemek olarak parmak yiyecekler.",
      },
      {
        id: 4,
        question: "Was bringt Clara mit?",
        options: ["Die Dekoration", "Die Getränke", "Die Geburtstagstorte"],
        correct: 2,
        explanation: "'du kannst die Torte besorgen' — Clara pastayı getirecek.",
      },
      {
        id: 5,
        question: "Mit welcher Füllung soll die Torte sein?",
        options: ["Mit Schokolade", "Mit Kirschen", "Mit Erdbeeren"],
        correct: 2,
        explanation: "'eine mit Erdbeeren, die mag Mama am liebsten' — anne çilekli pastayı çok seviyor.",
      },
    ],
    xp: 50,
  },
  {
    id: 23,
    type: "gespraeche",
    typeLabel: "Gespräch",
    typeLabelTr: "Konuşma",
    title: "Auf dem Amt",
    difficulty: 2,
    maleSpeakers: ["Herr König"],
    audioText:
      "Herr König: Guten Morgen, was kann ich für Sie tun?\nAna: Guten Morgen. Ich bin gerade nach Köln gezogen und möchte mich anmelden.\nHerr König: Natürlich. Haben Sie alle Dokumente dabei?\nAna: Ich habe meinen Reisepass und den Mietvertrag.\nHerr König: Gut. Haben Sie auch das ausgefüllte Anmeldeformular?\nAna: Nein, das wusste ich nicht. Tut mir leid.\nHerr König: Kein Problem, Sie können es hier ausfüllen. Hier ist das Formular.\nAna: Was muss ich alles eintragen?\nHerr König: Name, Geburtsdatum, alte und neue Adresse, und die Staatsangehörigkeit.\nAna: Wie lange dauert das?\nHerr König: Etwa fünf Minuten. Danach brauche ich nur noch Ihren Pass und den Mietvertrag, dann sind Sie fertig.\nAna: Wann bekomme ich die Meldebestätigung?\nHerr König: Sofort, noch heute. Sie können sie direkt mitnehmen.\nAna: Sehr gut! Muss ich dafür bezahlen?\nHerr König: Nein, die Anmeldung ist kostenlos.\nAna: Wunderbar. Dann fange ich gleich an.",
    instruction: "Sie hören ein Gespräch auf einem Amt. Wählen Sie die richtige Antwort.",
    questions: [
      {
        id: 1,
        question: "Was hat Ana vergessen mitzubringen?",
        options: ["Den Reisepass", "Das Anmeldeformular", "Den Mietvertrag"],
        correct: 1,
        explanation: "'das ausgefüllte Anmeldeformular' — Ana doldurulmuş kayıt formunu getirmeyi unutmuş.",
      },
      {
        id: 2,
        question: "Was muss Ana im Formular angeben?",
        options: ["Nur Name und Adresse", "Name, Geburtsdatum, Adresse und Staatsangehörigkeit", "Nur die neue Adresse"],
        correct: 1,
        explanation: "Name, Geburtsdatum, alte und neue Adresse und Staatsangehörigkeit — dört bilgi gerekiyor.",
      },
      {
        id: 3,
        question: "Wie lange dauert das Ausfüllen?",
        options: ["Etwa 2 Minuten", "Etwa 5 Minuten", "Etwa 15 Minuten"],
        correct: 1,
        explanation: "'Etwa fünf Minuten' — form doldurmak yaklaşık 5 dakika sürer.",
      },
      {
        id: 4,
        question: "Wann bekommt Ana die Meldebestätigung?",
        options: ["In drei Tagen", "Per Post", "Sofort, noch heute"],
        correct: 2,
        explanation: "'Sofort, noch heute. Sie können sie direkt mitnehmen' — adres tescil belgesi bugün hemen veriliyor.",
      },
      {
        id: 5,
        question: "Was kostet die Anmeldung?",
        options: ["5 Euro", "10 Euro", "Nichts"],
        correct: 2,
        explanation: "'die Anmeldung ist kostenlos' — adres tescili ücretsiz.",
      },
    ],
    xp: 50,
  },

  // ── A2 — Teile 24–30: Informationen ──────────────────────────────────────

  {
    id: 24,
    type: "informationen",
    typeLabel: "Radio-Interview",
    typeLabelTr: "Radyo Röportajı",
    title: "Deutsch lernen in Deutschland",
    difficulty: 2,
    maleSpeakers: ["Moderator"],
    audioText:
      "Moderator: Willkommen bei Radio Köln! Heute haben wir Fatima Yıldız zu Gast. Sie ist vor zwei Jahren aus der Türkei nach Deutschland gezogen. Fatima, warum haben Sie sich für Deutschland entschieden?\nFatima: Mein Mann arbeitet hier als Ingenieur. Deshalb sind wir nach Köln gezogen.\nModerator: Wie war Ihr Deutsch, als Sie ankamen?\nFatima: Ich konnte nur ein bisschen Deutsch. Ich habe A1 gemacht, aber das war nicht genug für den Alltag.\nModerator: Was haben Sie dann gemacht?\nFatima: Ich habe sofort einen Integrationskurs besucht. Der Kurs war dreimal in der Woche, immer morgens von neun bis zwölf Uhr.\nModerator: Hat der Kurs geholfen?\nFatima: Sehr! Nach sechs Monaten konnte ich gut einkaufen, Arzttermine machen und mit Nachbarn sprechen.\nModerator: Was war am schwierigsten?\nFatima: Die deutschen Artikel! Der, die, das — das ist wirklich schwer.\nModerator: Was machen Sie jetzt?\nFatima: Ich arbeite als Köchin in einem kleinen Restaurant. Und nebenbei mache ich jetzt B2.\nModerator: Das ist wunderbar! Vielen Dank, Fatima.\nFatima: Danke schön!",
    instruction: "Sie hören ein Radio-Interview. Wählen Sie die richtige Antwort.",
    questions: [
      {
        id: 1,
        question: "Warum ist Fatima nach Deutschland gezogen?",
        options: ["Sie wollte dort studieren.", "Ihr Mann arbeitet dort als Ingenieur.", "Sie hat dort Verwandte."],
        correct: 1,
        explanation: "'Mein Mann arbeitet hier als Ingenieur' — eşi mühendis olarak çalıştığı için taşınmışlar.",
      },
      {
        id: 2,
        question: "Wie oft war der Integrationskurs in der Woche?",
        options: ["Zweimal", "Dreimal", "Fünfmal"],
        correct: 1,
        explanation: "'Der Kurs war dreimal in der Woche' — entegrasyon kursu haftada 3 gün.",
      },
      {
        id: 3,
        question: "Was fand Fatima am schwierigsten?",
        options: ["Die deutschen Zahlen", "Die deutschen Artikel", "Die deutsche Aussprache"],
        correct: 1,
        explanation: "'Die deutschen Artikel! Der, die, das — das ist wirklich schwer.' — Almanca artikeller.",
      },
      {
        id: 4,
        question: "Was macht Fatima jetzt beruflich?",
        options: ["Sie ist Lehrerin.", "Sie ist Ärztin.", "Sie ist Köchin."],
        correct: 2,
        explanation: "'Ich arbeite als Köchin in einem kleinen Restaurant.' — küçük bir restorantta aşçı.",
      },
      {
        id: 5,
        question: "Welchen Deutschkurs macht Fatima jetzt?",
        options: ["A2", "B1", "B2"],
        correct: 2,
        explanation: "'jetzt mache ich B2' — şu anda B2 kursu yapıyor.",
      },
    ],
    xp: 50,
  },
  {
    id: 25,
    type: "informationen",
    typeLabel: "Radio-Interview",
    typeLabelTr: "Radyo Röportajı",
    title: "Gesund leben",
    difficulty: 2,
    maleSpeakers: ["Moderator"],
    audioText:
      "Moderator: Willkommen bei Fit im Alltag! Unser Gast heute ist Dr. Sandra Koch, Allgemeinmedizinerin aus Frankfurt. Dr. Koch, was ist der häufigste Fehler beim Thema Gesundheit?\nDr. Koch: Der größte Fehler ist definitiv zu wenig Bewegung. Die meisten meiner Patienten sitzen täglich acht bis zehn Stunden am Computer.\nModerator: Wie viel Bewegung braucht man pro Tag?\nDr. Koch: Die WHO empfiehlt mindestens dreißig Minuten moderate Bewegung täglich. Das kann ein Spaziergang sein, Fahrradfahren oder Schwimmen.\nModerator: Was ist mit Ernährung?\nDr. Koch: Auch sehr wichtig. Weniger Zucker und mehr Obst, Gemüse und Vollkornprodukte. Und bitte genug Wasser trinken — mindestens eineinhalb Liter täglich.\nModerator: Wie wichtig ist Schlaf?\nDr. Koch: Sehr wichtig! Erwachsene brauchen sieben bis acht Stunden pro Nacht. Schlafmangel schwächt das Immunsystem.\nModerator: Ein letzter Tipp?\nDr. Koch: Stress reduzieren! Meditation, Yoga oder ein Hobby helfen sehr.\nModerator: Vielen Dank, Dr. Koch!",
    instruction: "Sie hören ein Radio-Interview über Gesundheit. Wählen Sie die richtige Antwort.",
    questions: [
      {
        id: 1,
        question: "Was ist der häufigste Fehler laut Dr. Koch?",
        options: ["Zu viel essen", "Zu wenig Bewegung", "Zu wenig schlafen"],
        correct: 1,
        explanation: "'Der größte Fehler ist definitiv zu wenig Bewegung' — en büyük hata yetersiz hareket.",
      },
      {
        id: 2,
        question: "Wie viel Bewegung empfiehlt die WHO pro Tag?",
        options: ["15 Minuten", "30 Minuten", "60 Minuten"],
        correct: 1,
        explanation: "'mindestens dreißig Minuten moderate Bewegung täglich' — günde en az 30 dakika.",
      },
      {
        id: 3,
        question: "Wie viel Wasser soll man täglich trinken?",
        options: ["Mindestens 1 Liter", "Mindestens 1,5 Liter", "Mindestens 3 Liter"],
        correct: 1,
        explanation: "'mindestens eineinhalb Liter täglich' — günde en az 1,5 litre su.",
      },
      {
        id: 4,
        question: "Wie viele Stunden Schlaf brauchen Erwachsene?",
        options: ["5–6 Stunden", "7–8 Stunden", "9–10 Stunden"],
        correct: 1,
        explanation: "'sieben bis acht Stunden pro Nacht' — yetişkinler 7-8 saat uyumalı.",
      },
      {
        id: 5,
        question: "Was empfiehlt Dr. Koch gegen Stress?",
        options: ["Mehr Arbeit", "Meditation, Yoga oder ein Hobby", "Medikamente"],
        correct: 1,
        explanation: "'Meditation, Yoga oder ein Hobby helfen sehr' — meditasyon, yoga veya hobi stresi azaltır.",
      },
    ],
    xp: 50,
  },
  {
    id: 26,
    type: "informationen",
    typeLabel: "Radio-Interview",
    typeLabelTr: "Radyo Röportajı",
    title: "Deutsche Feste",
    difficulty: 2,
    maleSpeakers: ["Moderatorin", "Prof. Berger"],
    audioText:
      "Moderatorin: Willkommen bei Deutschland entdecken! Heute geht es um typisch deutsche Feste. Mit mir spricht Prof. Hans Berger, Kulturwissenschaftler. Professor Berger, welches Fest ist das bekannteste?\nProf. Berger: Das Oktoberfest in München natürlich! Es findet Ende September bis Anfang Oktober statt und dauert sechzehn Tage. Jedes Jahr kommen über sechs Millionen Besucher.\nModeratorin: Was macht das Oktoberfest besonders?\nProf. Berger: Das Bier, die Tracht — Dirndl und Lederhosen — und die Musik. Es ist ein Volksfest mit Fahrgeschäften und traditionellem Essen wie Brezeln und Würstchen.\nModeratorin: Welche anderen Feste sind typisch deutsch?\nProf. Berger: Karneval in Köln und Düsseldorf — da verkleiden sich die Leute und feiern auf den Straßen. Und Weihnachtsmärkte, die im Dezember in jeder Stadt stattfinden.\nModeratorin: Sind diese Feste auch für Touristen interessant?\nProf. Berger: Sehr! Millionen Touristen kommen speziell für diese Feste nach Deutschland.\nModeratorin: Danke, Professor Berger!",
    instruction: "Sie hören ein Radio-Interview über deutsche Feste. Wählen Sie die richtige Antwort.",
    questions: [
      {
        id: 1,
        question: "Wie lange dauert das Oktoberfest?",
        options: ["8 Tage", "12 Tage", "16 Tage"],
        correct: 2,
        explanation: "'dauert sechzehn Tage' — Oktoberfest 16 gün sürer.",
      },
      {
        id: 2,
        question: "Wie viele Besucher kommen jedes Jahr zum Oktoberfest?",
        options: ["Über 2 Millionen", "Über 4 Millionen", "Über 6 Millionen"],
        correct: 2,
        explanation: "'über sechs Millionen Besucher' — her yıl 6 milyondan fazla ziyaretçi gelir.",
      },
      {
        id: 3,
        question: "Was ist typische Kleidung beim Oktoberfest?",
        options: ["Anzug und Krawatte", "Dirndl und Lederhosen", "Jeans und T-Shirt"],
        correct: 1,
        explanation: "'Dirndl und Lederhosen' — geleneksel Bayern kıyafetleri.",
      },
      {
        id: 4,
        question: "Wo findet der Karneval statt?",
        options: ["In Berlin und Hamburg", "In Köln und Düsseldorf", "In München und Stuttgart"],
        correct: 1,
        explanation: "'Karneval in Köln und Düsseldorf' — Karneval, Köln ve Düsseldorf'ta kutlanır.",
      },
      {
        id: 5,
        question: "Wann finden Weihnachtsmärkte statt?",
        options: ["Im November", "Im Dezember", "Im Januar"],
        correct: 1,
        explanation: "'Weihnachtsmärkte, die im Dezember in jeder Stadt stattfinden' — Aralık ayında.",
      },
    ],
    xp: 50,
  },
  {
    id: 27,
    type: "informationen",
    typeLabel: "Radio-Interview",
    typeLabelTr: "Radyo Röportajı",
    title: "Öffentlicher Nahverkehr",
    difficulty: 2,
    maleSpeakers: ["Moderator"],
    audioText:
      "Moderator: Heute in unserer Sendung Mobil in Deutschland sprechen wir über den öffentlichen Nahverkehr. Zu Gast ist Verkehrsexpertin Dr. Petra Weiß. Dr. Weiß, wie gut ist der ÖPNV in Deutschland?\nDr. Weiß: In Großstädten wie Berlin, München oder Hamburg ist er sehr gut. U-Bahn, S-Bahn, Bus und Tram — alles ist gut vernetzt.\nModerator: Was kostet ein Monatsticket in München?\nDr. Weiß: Etwa fünfundneunzig Euro für das Stadtgebiet. In kleineren Städten ist es günstiger.\nModerator: Was ist das Deutschlandticket?\nDr. Weiß: Für neunundvierzig Euro im Monat kann man alle Nahverkehrsmittel in ganz Deutschland nutzen. Bus, Bahn, U-Bahn und Tram, überall.\nModerator: Hat der ÖPNV auch Schwächen?\nDr. Weiß: Ja, auf dem Land ist die Anbindung oft schlecht. Und pünktlich ist der Zug nicht immer — das ist ein bekanntes Problem.\nModerator: Vielen Dank, Dr. Weiß!",
    instruction: "Sie hören ein Radio-Interview über den öffentlichen Nahverkehr. Wählen Sie die richtige Antwort.",
    questions: [
      {
        id: 1,
        question: "In welchen Städten ist der ÖPNV besonders gut?",
        options: ["In kleinen Dörfern", "In Großstädten wie Berlin und München", "Auf dem Land"],
        correct: 1,
        explanation: "'In Großstädten wie Berlin, München oder Hamburg ist er sehr gut' — büyük şehirlerde toplu taşıma iyi.",
      },
      {
        id: 2,
        question: "Was kostet ein Monatsticket in München?",
        options: ["Etwa 65 Euro", "Etwa 95 Euro", "Etwa 125 Euro"],
        correct: 1,
        explanation: "'Etwa fünfundneunzig Euro für das Stadtgebiet' — Münih'te aylık bilet yaklaşık 95 €.",
      },
      {
        id: 3,
        question: "Was ist das Deutschlandticket?",
        options: ["Ein Ticket nur für Fernzüge", "Ein Ticket für alle Nahverkehrsmittel in Deutschland", "Ein Ticket für Touristen"],
        correct: 1,
        explanation: "'alle Nahverkehrsmittel in ganz Deutschland nutzen' — tüm yerel taşımacılık araçları için geçerli.",
      },
      {
        id: 4,
        question: "Wie viel kostet das Deutschlandticket?",
        options: ["29 Euro", "49 Euro", "99 Euro"],
        correct: 1,
        explanation: "'neunundvierzig Euro im Monat' — Almanya bileti aylık 49 €.",
      },
      {
        id: 5,
        question: "Was ist eine Schwäche des ÖPNV?",
        options: ["Es ist zu teuer.", "Schlechte Anbindung auf dem Land und Unpünktlichkeit", "Es gibt zu wenige Busse in Städten."],
        correct: 1,
        explanation: "'auf dem Land ist die Anbindung oft schlecht' ve 'pünktlich ist der Zug nicht immer' — iki zayıflık.",
      },
    ],
    xp: 50,
  },
  {
    id: 28,
    type: "informationen",
    typeLabel: "Radio-Interview",
    typeLabelTr: "Radyo Röportajı",
    title: "Arbeit und Beruf",
    difficulty: 2,
    maleSpeakers: ["Moderatorin", "Herr Neumann"],
    audioText:
      "Moderatorin: Heute spreche ich mit Berufsberater Klaus Neumann über den deutschen Arbeitsmarkt. Herr Neumann, welche Berufe sind besonders gefragt?\nHerr Neumann: Momentan suchen wir dringend Pflegekräfte, Ärzte, Ingenieure und IT-Experten. Das sind die größten Lücken.\nModeratorin: Wie hoch ist der durchschnittliche Lohn in Deutschland?\nHerr Neumann: Der durchschnittliche Bruttolohn liegt bei etwa dreitausendneunhundert Euro pro Monat. Das variiert stark nach Beruf und Region.\nModeratorin: Was ist der gesetzliche Mindestlohn?\nHerr Neumann: Aktuell zwölf Euro fünfzig pro Stunde. Das ist eine wichtige Untergrenze.\nModeratorin: Was raten Sie Menschen, die in Deutschland arbeiten möchten?\nHerr Neumann: Erstens: Sprachkenntnisse sind entscheidend. Ohne Deutsch ist es sehr schwer. Zweitens: Lassen Sie Ihre Abschlüsse anerkennen.\nModeratorin: Gibt es Hilfe für Neuankömmlinge?\nHerr Neumann: Ja, die Bundesagentur für Arbeit bietet kostenlose Beratung und Kurse an.\nModeratorin: Herzlichen Dank, Herr Neumann!",
    instruction: "Sie hören ein Radio-Interview über Arbeit und Beruf. Wählen Sie die richtige Antwort.",
    questions: [
      {
        id: 1,
        question: "Welche Berufe sind laut Herrn Neumann besonders gefragt?",
        options: ["Lehrer und Künstler", "Pflegekräfte, Ärzte, Ingenieure, IT-Experten", "Verkäufer und Kassierer"],
        correct: 1,
        explanation: "'Pflegekräfte, Ärzte, Ingenieure und IT-Experten' — bu mesleklerde büyük açık var.",
      },
      {
        id: 2,
        question: "Wie hoch ist der durchschnittliche Bruttolohn?",
        options: ["Etwa 2.500 Euro", "Etwa 3.900 Euro", "Etwa 5.000 Euro"],
        correct: 1,
        explanation: "'etwa dreitausendneunhundert Euro pro Monat' — ortalama brüt maaş yaklaşık 3.900 €.",
      },
      {
        id: 3,
        question: "Wie hoch ist der Mindestlohn pro Stunde?",
        options: ["10,50 Euro", "12,50 Euro", "15,00 Euro"],
        correct: 1,
        explanation: "'Aktuell zwölf Euro fünfzig pro Stunde' — asgari ücret saate 12,50 €.",
      },
      {
        id: 4,
        question: "Was ist der erste Rat für Menschen, die in Deutschland arbeiten möchten?",
        options: ["Viel Geld sparen", "Deutsch lernen", "Eine Wohnung finden"],
        correct: 1,
        explanation: "'Sprachkenntnisse sind entscheidend. Ohne Deutsch ist es sehr schwer.' — Almanca öğrenmek şart.",
      },
      {
        id: 5,
        question: "Wer bietet kostenlose Beratung für Neuankömmlinge?",
        options: ["Das Finanzamt", "Die Bundesagentur für Arbeit", "Die Stadtverwaltung"],
        correct: 1,
        explanation: "'die Bundesagentur für Arbeit bietet kostenlose Beratung an' — Bundesagentur für Arbeit ücretsiz danışmanlık sunar.",
      },
    ],
    xp: 50,
  },
  {
    id: 29,
    type: "informationen",
    typeLabel: "Radio-Interview",
    typeLabelTr: "Radyo Röportajı",
    title: "Familie in Deutschland",
    difficulty: 2,
    maleSpeakers: ["Moderator"],
    audioText:
      "Moderator: Willkommen bei Familie heute! Heute spreche ich mit Soziologin Prof. Maria Huber über Familie in Deutschland. Prof. Huber, wie hat sich die Familie verändert?\nProf. Huber: Die Familie ist kleiner geworden. Früher hatten Familien drei oder vier Kinder, heute sind es durchschnittlich nur noch ein oder zwei.\nModerator: Was sind die größten Herausforderungen?\nProf. Huber: Die Vereinbarkeit von Beruf und Familie ist schwierig. Viele Eltern möchten arbeiten, aber es gibt zu wenig Kindergartenplätze.\nModerator: Was bekommt man in Deutschland für Kinder?\nProf. Huber: Es gibt das Kindergeld — zweihundertfünfzig Euro pro Monat für jedes Kind. Das ist eine wichtige Unterstützung.\nModerator: Wie lange kann man Elternzeit nehmen?\nProf. Huber: Eltern haben das Recht auf bis zu drei Jahre Elternzeit. In dieser Zeit ist der Arbeitsplatz sicher.\nModerator: Was wünschen sich Familien?\nProf. Huber: Mehr Kindergartenplätze, flexiblere Arbeitszeiten und günstigere Wohnungen.\nModerator: Danke, Prof. Huber!",
    instruction: "Sie hören ein Radio-Interview über Familie in Deutschland. Wählen Sie die richtige Antwort.",
    questions: [
      {
        id: 1,
        question: "Wie viele Kinder haben Familien in Deutschland heute durchschnittlich?",
        options: ["3–4 Kinder", "1–2 Kinder", "5 oder mehr Kinder"],
        correct: 1,
        explanation: "'heute sind es durchschnittlich nur noch ein oder zwei' — ortalama 1-2 çocuk.",
      },
      {
        id: 2,
        question: "Was ist ein großes Problem für Familien?",
        options: ["Zu wenig Geld", "Zu wenig Kindergartenplätze", "Zu wenig Schulen"],
        correct: 1,
        explanation: "'es gibt zu wenig Kindergartenplätze' — kreş yeri yetersizliği büyük problem.",
      },
      {
        id: 3,
        question: "Wie viel Kindergeld gibt es pro Kind?",
        options: ["150 Euro", "250 Euro", "350 Euro"],
        correct: 1,
        explanation: "'zweihundertfünfzig Euro pro Monat für jedes Kind' — her çocuk için aylık 250 € çocuk parası.",
      },
      {
        id: 4,
        question: "Wie lange darf man Elternzeit nehmen?",
        options: ["Bis zu 1 Jahr", "Bis zu 2 Jahre", "Bis zu 3 Jahre"],
        correct: 2,
        explanation: "'bis zu drei Jahre Elternzeit' — ebeveyn izni en fazla 3 yıl.",
      },
      {
        id: 5,
        question: "Was wünschen sich Familien?",
        options: ["Mehr Schulen und bessere Lehrer", "Mehr Kitas, flexiblere Arbeitszeiten, günstige Wohnungen", "Mehr öffentliche Parks"],
        correct: 1,
        explanation: "Üç dilek: daha fazla kreş, esnek çalışma saatleri ve uygun fiyatlı konut.",
      },
    ],
    xp: 50,
  },
  {
    id: 30,
    type: "informationen",
    typeLabel: "Radio-Interview",
    typeLabelTr: "Radyo Röportajı",
    title: "Essen und Kochen",
    difficulty: 3,
    maleSpeakers: ["Moderator"],
    audioText:
      "Moderator: Willkommen bei Essen und Trinken! Zu Gast ist Köchin und Buchautorin Julia Schwarz. Frau Schwarz, was ist typisch deutsche Küche?\nJulia: Deutsche Küche ist deftig und bodenständig. Denken Sie an Bratwurst, Sauerkraut, Schnitzel und Kartoffeln in allen Variationen.\nModerator: Hat sich die deutsche Küche verändert?\nJulia: Absolut! Deutschland ist ein Einwanderungsland, und das merkt man in der Küche. Döner Kebab wurde in Deutschland erfunden und ist das beliebteste Fast Food.\nModerator: Was kochen die Deutschen zu Hause?\nJulia: Laut Studien kocht ein Drittel der Deutschen täglich frisch. Ein weiteres Drittel kocht ein bis zweimal pro Woche.\nModerator: Gibt es regionale Unterschiede?\nJulia: Ja, sehr! Bayern hat Weißwurst und Brezeln. Im Norden gibt es viel Fisch. Im Rheinland: Sauerbraten.\nModerator: Was ist Ihr Lieblingsrezept für Anfänger?\nJulia: Kartoffelsuppe! Kartoffeln kochen, pürieren, Gewürze und Sahne dazu — fertig. Einfach, günstig und lecker.\nModerator: Vielen Dank, Frau Schwarz!",
    instruction: "Sie hören ein Radio-Interview über Essen und Kochen. Wählen Sie die richtige Antwort.",
    questions: [
      {
        id: 1,
        question: "Wie beschreibt Julia Schwarz die deutsche Küche?",
        options: ["Leicht und frisch", "Deftig und bodenständig", "Scharf und exotisch"],
        correct: 1,
        explanation: "'deftig und bodenständig' = ağır ve geleneksel. Bratwurst, Schnitzel, Kartoffeln.",
      },
      {
        id: 2,
        question: "Was ist das beliebteste Fast Food in Deutschland?",
        options: ["Hamburger", "Döner Kebab", "Pizza"],
        correct: 1,
        explanation: "'Döner Kebab wurde in Deutschland erfunden und ist das beliebteste Fast Food' — Döner Kebab Almanya'da icat edildi.",
      },
      {
        id: 3,
        question: "Wie oft kocht ein Drittel der Deutschen?",
        options: ["Nie", "Täglich frisch", "Nur am Wochenende"],
        correct: 1,
        explanation: "'kocht ein Drittel der Deutschen täglich frisch' — üçte biri her gün taze pişiriyor.",
      },
      {
        id: 4,
        question: "Was ist eine typische Spezialität aus Bayern?",
        options: ["Sauerbraten", "Fischbrötchen", "Weißwurst und Brezeln"],
        correct: 2,
        explanation: "'Bayern hat Weißwurst und Brezeln' — Bavyera'nın geleneksel yemeği.",
      },
      {
        id: 5,
        question: "Was empfiehlt Julia Schwarz für Kochanfänger?",
        options: ["Schnitzel", "Kartoffelsuppe", "Sauerbraten"],
        correct: 1,
        explanation: "'Kartoffelsuppe! Einfach, günstig und lecker' — patates çorbası kolay, ucuz ve lezzetli.",
      },
    ],
    xp: 60,
  },
];

// ── Accessor helpers ──────────────────────────────────────────────────────────

const LEVEL_DATA: Record<string, HorenTeil[]> = {
  a2: A2_TEILE,
};

export function getHorenTeile(level: string): HorenTeil[] {
  return LEVEL_DATA[level.toLowerCase()] ?? [];
}

export function getHorenTeil(level: string, id: number): HorenTeil | undefined {
  return getHorenTeile(level).find((t) => t.id === id);
}

// ── Progress (localStorage) ───────────────────────────────────────────────────

export function loadHorenProgress(level: string): HorenProgress {
  if (typeof window === "undefined") return {};
  try {
    return JSON.parse(localStorage.getItem(`horen-progress-${level}`) ?? "{}");
  } catch {
    return {};
  }
}

export function saveHorenProgress(
  level: string,
  teilId: number,
  score: number,
  total: number
) {
  if (typeof window === "undefined") return;
  const prev = loadHorenProgress(level);
  localStorage.setItem(
    `horen-progress-${level}`,
    JSON.stringify({ ...prev, [teilId]: { score, total } })
  );
}
